### ISSUE TITLE
Use the new Azure SDK

### ISSUE THREAD

**Issue by jasmingoh** [Microsoft/WebTemplateStudio#1015]
Update code to use this SDK (https://github.com/Azure/azure-sdk-for-js) instead. The SDK that we are using has been deprecated since July 2019 (https://github.com/azure/azure-sdk-for-node)

**Comment by sibille** [comment]
https://github.com/Azure/azure-sdk-for-js/blob/master/documentation/Migration.md

**Comment by dgomezc** [comment]
Currently blocked on microsoft/vscode-azure-account#140

**Comment by sibille** [comment]
Verified in nightly version:
Templates version: 0.3.21131.1
Wizard version: 0.3.2113101
