### ISSUE TITLE
Add read-only project name to right sidebar on summary

### ISSUE THREAD

**Issue by xtinah-w** [Microsoft/WebTemplateStudio#1030]
Users should know what they saved their project as (name-wise)

**Comment by streetcoder123** [comment]
@xtinah-w Can you upload a mock for this?

**Comment by xtinah-w** [comment]
![projectDetails-projectNameLocation](https://user-images.githubusercontent.com/24245311/62741474-e1e95b80-b9ef-11e9-9a5a-6631144f87b2.png)
