### ISSUE TITLE
Font size feels off in Learn more page

### ISSUE THREAD

**Issue by SahilTara** [Microsoft/WebTemplateStudio#1040]
Outside of learn more:
![image](https://user-images.githubusercontent.com/32103099/62673798-c9d0f800-b96d-11e9-966a-9de43dbbc514.png)

Inside of learn more:
![image](https://user-images.githubusercontent.com/32103099/62673850-f422b580-b96d-11e9-98b7-1ea1d67a99b1.png)

I think the font size should be larger here. Back button should also be higher up.

**Comment by streetcoder123** [comment]
@xtinah-w Thoughts?

**Comment by xtinah-w** [comment]
Yeah, agreed! I'll update the design right after I finish post-generation modal and Azure Resource forms :)
