### ISSUE TITLE
Azure App Service + Cosmos form - missing error message on empty site name 

### ISSUE THREAD

**Issue by jsondoo** [Microsoft/WebTemplateStudio#1048]
Currently if the name field is empty, there is no message, we just show a spinner. We should provide some feedback with a message like "Name cannot be empty"

![image](https://user-images.githubusercontent.com/21695878/62733040-a3957180-b9da-11e9-99ac-3eb1bdaf88ac.png)

Current Status:
![AzureNameMessage](https://user-images.githubusercontent.com/1333036/123231381-7243c300-d4d8-11eb-8b61-61c4debc2846.gif)

**Comment by prupipho** [comment]
Still happening something similar. No message if you empty the Name box in both App Service or Cosmos Modal.
It doesn´t allow you to continue but it doesn´t display any error message or provide any feedback to know what to do next.

![image](https://user-images.githubusercontent.com/1333036/96703420-1d710b00-1393-11eb-9e36-58272193a1d3.png)

Could be an easy one to fit within next milestone @sibille ? As we are still refactoring and changing the Azure section?

**Comment by sibille** [comment]
Agree, an empty name should show an error message here

**Comment by prupipho** [comment]
Tested on nightly version:
Templates version: 0.3.21167.1
Wizard version: 0.3.2116701

![image](https://user-images.githubusercontent.com/1333036/122205579-b3b4ec80-cea0-11eb-8f41-35239b3d295e.png)

![image](https://user-images.githubusercontent.com/1333036/122205549-a7c92a80-cea0-11eb-95ef-3d6556220a83.png)
