### ISSUE TITLE
Azure forms - code improvements

### ISSUE THREAD

**Issue by jsondoo** [Microsoft/WebTemplateStudio#1049]
Currently the azure services forms are hard to maintain because they are all separate components despite sharing the same logic, styles, etc. This means that if you want to change a button placement, or some behavior for the form, it has to be applied to all the form files separately. It would be nice to have some of this refactored, so that it shares certain things between the forms.

It would also be nice to look into clean up our React hooks - right now we have a lot of hooks with different states (which are updated asynchronously), hooks that communicate with the extension, and hooks that use timeout, and all of this combined makes it easy to cause race conditions issues which makes our forms hard to maintain and debug.

**Comment by SahilTara** [comment]
I feel like you shouldn't move away from hooks. Hooks are the direction Facebook seems to be taking React. I would restructure the use of hooks though. Hooks that use timeout seems a bit weird. I do agree that you should abstract some functionality out too, so much reused code. @jsondoo What do you think?

**Comment by jsondoo** [comment]
@SahilTara yea, just some restructuring might be better. In my experience with hooks (at least with the forms) is that it was hard to keep track of what is happening with all the stuff I mentioned, so maybe some clean-up would make it more maintainable. But I agree, they're very useful and simple way to keep track of its own state.

**Comment by sibille** [comment]
Azure forms code was refactored as part of #1411
