### ISSUE TITLE
Postgen modal azure links don't redirect correctly

### ISSUE THREAD

**Issue by jsondoo** [Microsoft/WebTemplateStudio#1062]
The links we have for the 3 services are:
1) Functions: https://portal.azure.com/#blade/WebsitesExtension/FunctionsIFrameBladeMain
2) Cosmos DB: https://portal.azure.com/#blade/HubsExtension/BrowseResourceBlade/resourceType/Microsoft.DocumentDb%2FdatabaseAccounts
3) App Service: https://ms.portal.azure.com/#blade/HubsExtension/BrowseResourceBlade/resourceType/Microsoft.Web%2Fsites

CosmosDB and App Service link takes you to the "All Resources" page rather than the "Cosmos DB" or "App Service" resource group pages when clicked on through the VSCode extension.

VSCode Issue: https://github.com/microsoft/vscode/issues/45515
VSCode currently decodes the `%2F` into a slash, so it takes you to a different path.

**Comment by SahilTara** [comment]
By the way you might want to change `ms.portal.azure.com/` to `portal.azure.com`

**Comment by SahilTara** [comment]
Hmm odd, not sure if i understand the issue.
![image](https://user-images.githubusercontent.com/32103099/62816458-cff1e080-baf5-11e9-9de2-d93869f0af16.png)
is this not the right page? (Clicked on client side)

**Comment by jsondoo** [comment]
@SahilTara that is the right page, it seems to work when you click on the link on the running it on the browser, but for some reason it takes you somewhere else when you click the link through the vscode extension

**Comment by SahilTara** [comment]
Hmm that's really strange

**Comment by jsondoo** [comment]
It seems like if you left click it takes you to the 'All Resources', if you do middle click it takes you to the correct places. Possible solution might be just change it to an <a /> tag rather than ReactMarkdown

**Comment by jsondoo** [comment]
This is an issue with VSCode so waiting on them to fix it (or maybe there's a workaround)
Basically, VSCode decodes the '%2F' in the link into a slash

https://github.com/microsoft/vscode/issues/25852#issuecomment-462167101

**Comment by SahilTara** [comment]
Think you mean to add https://github.com/microsoft/vscode/issues/45515 (if you scroll down in the link you posted they track decoding on the linked issue).

**Comment by jsondoo** [comment]
> Think you mean to add [microsoft/vscode#45515](https://github.com/microsoft/vscode/issues/45515) (if you scroll down in the link you posted they track decoding on the linked issue).

Thanks, updated

**Comment by sibille** [comment]
VSCode tracking issue is https://github.com/microsoft/vscode/issues/83645

**Comment by jrieken** [comment]
@sibille How do you open these links? Via `vscode.env.openExternal` or as links that the editor detects?

**Comment by sibille** [comment]
@jrieken I'd say a link that the editor detects: Link is shown in a react app running in the webview. Link rendering code in question is : https://github.com/microsoft/WebTemplateStudio/blob/b51ca65604f70e3646692067179ae08a4f69d832/src/client/src/containers/PostGenerationModal/index.tsx#L86

**Comment by jrieken** [comment]
Can you try with latest insiders? That should have a fix for these issues

**Comment by sibille** [comment]
I tested with Insiders 1.41 and this seems still broken.
Source html is 
`<a href="https://portal.azure.com/#blade/HubsExtension/BrowseResourceBlade/resourceType/Microsoft.Web%2Fsites" class="styles_link__3M7Qr">View</a>`

but then shows as

![image](https://user-images.githubusercontent.com/24698018/69722421-62ef6e80-1117-11ea-954b-259c698d0840.png)

**Comment by jrieken** [comment]
The link that get's shown there must not be the link that gets opened, e.g the encoding in the dialog is likely different but I assume that opening is also not working, right? Is that html from an embedded webview?

**Comment by sibille** [comment]
I just double checked, the link is the same in the browser, so its not opening correct. 

> Is that html from an embedded webview?

Yes, Web Template Studio is shown in the embedded webview

**Comment by jrieken** [comment]
check - this should be better with next (Mondays) insiders build, https://github.com/microsoft/vscode/issues/83645#issuecomment-559814023

**Comment by sibille** [comment]
Working now on todays insider build. 
Version: 1.41.0-insider (user setup)
Commit: 7cf4cca47aa025a590fc939af54932042302be63

The link is still showing up wrong in the popup, but leads to the correct place
![image](https://user-images.githubusercontent.com/24698018/69967040-ea721e80-1517-11ea-9f39-887ae63ed249.png)
![image](https://user-images.githubusercontent.com/24698018/69967086-fe1d8500-1517-11ea-8812-90abdf5d27c3.png)
Thanks @jrieken!

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.2.20120.1
Wizard version: 0.2.2012001

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.2.20120.1
Wizard version: 0.2.2012001
