### ISSUE TITLE
Accessibility Issues

### ISSUE THREAD

**Issue by Tanya0609** [Microsoft/WebTemplateStudio#1063]
- [x] Next button in the footer should redirect to the top of the panel rather than staying in the footer
- [ ] Azure Services Forms: add heading/label to enhance navigation; show focus for radio button and input files; at the moment when you select a resource group from drop down and hit the enter, it changes the focus and focus goes back to the background page

**Comment by sibille** [comment]
We don't have resource group dropdown and the Azure Service Form keyboard navigation works fine.
