### ISSUE TITLE
Modify Azure Service Text in Right Sidebar 

### ISSUE THREAD

**Issue by streetcoder123** [Microsoft/WebTemplateStudio#1080]
Currently, on the summary page (in the right sidebar), the Services section looks like this:

![image](https://user-images.githubusercontent.com/35667299/62973883-dfaa4700-bdcb-11e9-804c-eb64a192bcb6.png)

- The button seems like it is disabled.
- Text needs to be improved to make it apparent that it is optional to add services.

**Comment by sibille** [comment]
I think we should not show the services category if no services were added.

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.1.20055.2
Wizard version: 0.1.2005502
