### ISSUE TITLE
Add more App Service related instruction in generated README.md

### ISSUE THREAD

**Issue by Tanya0609** [Microsoft/WebTemplateStudio#1081]
- What happens if you project without app service selected? It will build the project and deploy as App Service Extension full steps
- Where to get the URL
- Is the popup stick around? Include to the README just in case they miss the popup

**Comment by jasmingoh** [comment]
> What happens if you project without app service selected? It will build the project and deploy as App Service Extension full steps

Yup, just added that step to the generated README


> Where to get the URL
> Is the popup stick around? Include to the README just in case they miss the popup


We will need to talk more about this

**Comment by Tanya0609** [comment]
This is has been done, thus close.
