### ISSUE TITLE
Remove yellow highlight on selection 

### ISSUE THREAD

**Issue by xtinah-w** [Microsoft/WebTemplateStudio#1086]
Causes too much confusion and uncertainty which we've gotten feedback on during user testing

**Comment by SahilTara** [comment]
Maybe change the thickness when you focus or enlarge the selected object instead or a combo of both (assuming this is for selections of pages and such).

**Comment by xtinah-w** [comment]
@SahilTara Yeah, I think the general consensus though from the user testing is to just remove the yellow highlight entirely since "selection" is signified by the green checkmark + thick white border showing the selection, so there doesn't need to be a 3rd visual cue that just keeps appearing/disappearing.

**Comment by SahilTara** [comment]
Hmm I think it's there more so to give a clear indicator for what is in focus when using tab navigation, so is removing the best choice here? @xtinah-w

**Comment by xtinah-w** [comment]
Tab navigation is different from active selection and the yellow highlight on click isn't a behaviour that exists in VS Code itself. I agree that tab navigation should have a blue active border (VS Code default active colour), but the yellow highlight isn't needed since there's already an active state that's visually shown when they select something (thick white border + green checkmark). The only other affordance I can think of is a hover state which I've also designed, but probably won't be implemented in our wizard.

**Comment by SahilTara** [comment]
I think the yellow border appearing is due to the :focus being used for tab navigation. It does help with tabs but it has the unwanted side affect of the yellow artifact on click. We'll need to come up with a way to only disable it for on click, but keep it for tab navigation. Possibly change the colour too (right now it is set to be contrast) as you said, maybe not blue per-say as it would not contrast well with our blue buttons.

**Comment by SahilTara** [comment]
Hey @xtinah-w I removed the yellow highlights off of the selected items. (Frameworks and such). Can you confirm or let me know anything else you want the yellow highlights off of. Kept it for tab nav. Removed for on click. On click you get the white border only, on tab you get the yellow one.
