### ISSUE TITLE
extension UI: page naming validation alter overlap with other pages

### ISSUE THREAD

**Issue by Tanya0609** [Microsoft/WebTemplateStudio#1100]
How to reproduce: 
1. go to the extension and select multiple pages
2. try to rename one of the page with more than 50 chars

![error-message-overlapping](https://user-images.githubusercontent.com/12874317/63123258-68a4b800-bf5d-11e9-83d9-9c9e05310ce9.PNG)

**Comment by sibille** [comment]
We should use the same behaviour on validation errors as VS Code uses. If you try to rename a file in VS Code to an invalid name the textbox shows like this: 
![image](https://user-images.githubusercontent.com/24698018/69954909-c7864100-14fc-11ea-8f40-6ee8793b2d47.png)
Clicking outside the box cancels the renaming operation.

**Comment by sibille** [comment]
Fixed as part of #1309

Verified in dev-nightly:
Templates version: 0.1.20028.1
Wizard version: 0.1.2002801
