### ISSUE TITLE
Having emojis in 'Save To' path, then generating and opening project fails

### ISSUE THREAD

**Issue by jsondoo** [Microsoft/WebTemplateStudio#1103]
Steps To Reproduce
1) Create a new folder with unicode characters in the folder name
2) Select that folder to be your 'Save To' path
3) Click 'Create Project' then 'Open Project'

![image](https://user-images.githubusercontent.com/21695878/63126916-e4a2fe00-bf65-11e9-88a3-8fb94f52437c.png)

**Comment by PhaseRush** [comment]
nooo not my emoji files :(

**Comment by SahilTara** [comment]
Haha yeah we experimented with emojis. We tried to block the user from being able to input emojis and such because we knew it broke stuff. I think at one point we tried out emoji project names and such. Didn't end well 😂. "🔥 🔥" was our test project name to break all the things.

**Comment by SahilTara** [comment]
Just wondering does anything happen when having non-english characters that fall into the unicode spectrum in the path?

**Comment by jsondoo** [comment]
> Just wondering does anything happen when having non-english characters that fall into the unicode spectrum in the path?

Yea, stuff like chinese characters will fail
