### ISSUE TITLE
Dragging pages on the right side bar makes the item being dragged go under the right side bar

### ISSUE THREAD

**Issue by jsondoo** [Microsoft/WebTemplateStudio#1104]
![Screenshot (33)](https://user-images.githubusercontent.com/21695878/63127900-7c095080-bf68-11e9-8f6d-1dad8bc8fc39.png)

**Comment by SahilTara** [comment]
Z index?

**Comment by sibille** [comment]
X-Ref:  https://github.com/microsoft/WebTemplateStudio/issues/671

**Comment by sibille** [comment]
Verified in dev-nightly version: 
Templates version: 0.0.19329.1
Wizard version: 0.0.1932901
