### ISSUE TITLE
Right Sidebar closes abruptly when deleting pages

### ISSUE THREAD

**Issue by streetcoder123** [Microsoft/WebTemplateStudio#1105]
Steps to Reproduce:
- Add a few pages to an application
- Remove pages from the right sidebar
- As soon as 1 page is left, the sidebar closes abruptly
- Then, as you add a page, it abruptly appears again.

**Comment by SahilTara** [comment]
What is intended? Once pages modified it remains open, unless otherwise closed?

**Comment by streetcoder123** [comment]
Yeah, I think the ideal behavior should be to open the sidebar once the user starts to modify the pages and keep it open there after until explicitly closed.
What do you think @xtinah-w ?
