### ISSUE TITLE
Closed right sidebar is still tabbable

### ISSUE THREAD

**Issue by ali-kha** [Microsoft/WebTemplateStudio#1106]
Steps to Reproduce:
1. Go to any page with a collapsible sidebar
2. Have the sidebar be closed
3. Tab through the page
4. When tabbing seems to be invisible, the tab is in the sidebar, try counting tabs and doing things like changing frameworks, etc as if the sidebar was open.

**Comment by streetcoder123** [comment]
@ali-kha This is fixed, right?

**Comment by jsondoo** [comment]
fixed with #1108
