### ISSUE TITLE
Add Error Handling for Web Template Studio: Deploy App Command

### ISSUE THREAD

**Issue by streetcoder123** [Microsoft/WebTemplateStudio#1107]
Currently, the command does not show any errors if any of the processes like below fail.
- `npm install`
- `npm run-script build`

We need to add error handling for this so that we can tell the user that deployment is unsuccessful with a reasonable error message.

**Comment by sibille** [comment]
Done in PR https://github.com/microsoft/WebTemplateStudio/pull/1219
