### ISSUE TITLE
Could not sync to template repository

### ISSUE THREAD

**Issue by paul0027** [Microsoft/WebTemplateStudio#1125]
Repro steps:

1.
2.

Action: Sync-Engine
Error type: Error
Error Message: Could not sync to template repository

Version: 0.0.1922901
OS: win32
VS Code Version: 1.37.1

<details>
<summary>Call Stack</summary>

```
LaunchExperience.<anonymous> (C:/Users/<user>/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.0.1922901/out/launchExperience.js:40:23)
Generator.next (<anonymous>)
fulfilled (C:/Users/enald/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.0.1922901/out/launchExperience.js:4:58)
```

</details>

**Comment by SahilTara** [comment]
@Tanya0609 Regression of #601? Or do you think this is a different issue?

**Comment by Tanya0609** [comment]
@Bagobie , thanks for reporting.
Could you try restart the extension and see if the error still happens?

If so, some more questions to further diagnose and try to repro:

- What exact OS version are you using?
- Do you see any logs in the folder "/Users/[username]/.local/share/WebTS/Logs"? Could you share them?

**Comment by andreifilip123** [comment]
Check out #601

**Comment by Tanya0609** [comment]
@SahilTara, it seems like they are the same issue based on the call stack

**Comment by Tanya0609** [comment]
Hi @Bagobie,

Those are the steps to resolve this issue (same steps as mentioned in #601):
1. Do you see any logs in the folder "/Users/[username]/.local/share/WebTS/Logs"? Could you share them? (it is a hidden file on Mac, not sure about win32)


2. /Users/[username]/.local/share/WebTS/ is the folder where templates are synchronized. Does your user have write permissions on /Users/[username]/.local/share?

3. If you have the permission, you could create the folder manually. `mkdir -p ~/.local/share/WebTS` and restart VS Code. 

Then it should work for you. Please let me know if you have any more question!

**Comment by SahilTara** [comment]
> Hi @Bagobie,
> 
> Those are the steps to resolve this issue (same steps as mentioned in #601):
> 
> 1. Do you see any logs in the folder "/Users/[username]/.local/share/WebTS/Logs"? Could you share them? (it is a hidden file on Mac, not sure about win32)

For windows its: %LocalAppData%\WebTS\Logs

**Comment by sibille** [comment]
Is this still an issue? 
	
Were missing permissions on 
	
```
Mac: /Users/[username]/.local/share
Linux: //home/[username]/.local/share
Windows:  %LocalAppData%
```
	
the underlying reason or did you have to change anything else?
	
Opened issue https://github.com/microsoft/WebTemplateStudio/issues/1182 to improve user feedback.

**Comment by dgomezc** [comment]
We have published a new version of Web Template Studio that fix some errors with template synchronization. Error management has also been improved to include more info.

If you have template synchronization problems again, please opened a new issue.
