### ISSUE TITLE
Unable to debug extension

### ISSUE THREAD

**Issue by michael-watson** [Microsoft/WebTemplateStudio#1127]
I'm unable to launch/debug on the dev/staging branch. I was hoping to contribute some templates. Is this a known issue?

My error:
```
[8/21/2019, 8:49:55 PM][EXTENSION] Launched
[8/21/2019, 8:49:55 PM][EXTENSION] Error: ENOENT: no such file or directory, chmod '/Users/michaelwatson/Documents/GitHub/WebTemplateStudio/src/extension/src/corets-cli/darwin/Microsoft.Templates.Cli'
```

**Comment by SahilTara** [comment]
Hey, thanks for the issue.
I think you should check out [our getting started for developers](https://github.com/microsoft/WebTemplateStudio/blob/dev/docs/getting-started-developers.md).

If you have all the pre requisites there try doing ./build and debugging again (or follow the detailed steps). Let us know if the problem persists!

**Comment by Tanya0609** [comment]
This file is from our git submodule.

You would need to do _git submodule init_ and _git submodule update_

More instructions can be found in the link provided by @SahilTara

**Comment by Tanya0609** [comment]
I will close this issue first, please let us know if you have any more question :)

**Comment by michael-watson** [comment]
I should have clarified, but I did follow those instructions closely. Just read and followed them again to receive the same error.

Here is a gist of my terminal output from the setup. 
https://gist.github.com/michael-watson/14e84a62faea71f4c12b30d39a9f5666

Also shows I have that submodule active from the status:
```
Michaels-MBP-3:WebTemplateStudio michaelwatson$ git submodule status
 22b73c47f5a012e138bf42ed754cdd3e195f3575 src/CoreTemplateStudio (heads/dev)
```

**Comment by michael-watson** [comment]
I should also note that your tests pass successfully, but still get the error trying to launch the webtemplatestudio

<img width="791" alt="Screen Shot 2019-08-22 at 8 05 05 PM" src="https://user-images.githubusercontent.com/8645958/63564031-417b5700-c518-11e9-9e4e-b8aa9d6b4d6f.png">

**Comment by SahilTara** [comment]
`The current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 2.1 or lower`
Seems like your version is lower than the supported version. [Try it out with .NET Core 2.2](https://dotnet.microsoft.com/download/dotnet-core/2.2)

**Comment by michael-watson** [comment]
I think my problem was I have Visual Studio for Mac installed also and the dotnet SDK was out of sync. I can verify that installing versions 2.2.401 .NET Core SDK and the 2.2.6 .NET Runtime are working for me. Thanks for your help.
