### ISSUE TITLE
React-Redux option

### ISSUE THREAD

**Issue by mmcelroy90** [Microsoft/WebTemplateStudio#1129]
It would be awesome to have an option to use React-Redux (TypeScript and JS versions) when selecting a React app. Ideally this would also come with a few pre-built pages for initial store setup, etc.

I believe the initial setup is non-trivial and it is popular enough to be a useful feature.

**Comment by Tanya0609** [comment]
Hi @mmcelroy90, thanks for the feedback, this is a great idea! We will log them in our backlog.
