### ISSUE TITLE
Error: Could not sync to template repository

### ISSUE THREAD

**Issue by marcoholmes** [Microsoft/WebTemplateStudio#1132]
Repro steps:

1.
2.

Action: Sync-Engine
Error type: Error
Error Message: Could not sync to template repository

Version: 0.0.1922901
OS: win32
VS Code Version: 1.37.1

<details>
<summary>Call Stack</summary>

```
LaunchExperience.<anonymous> (c:/Users/u1100694/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.0.1922901/out/launchExperience.js:40:23)
Generator.next (<anonymous>)
fulfilled (c:/Users/u1100694/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.0.1922901/out/launchExperience.js:4:58)
```

</details>

**Comment by Tanya0609** [comment]
Hi @marcoholmes, thank you for reporting!

Could you try restart the extension and see if the error still happens?

If so, some more questions to further diagnose and try to repro:

- What exact OS version are you using?
- Do you see any logs in the folder "/Users/[username]/.local/share/WebTS/Logs"? Could you share them? 
Edited: the path is %LocalAppData%\WebTs\Logs for windows

**Comment by CodeBroJohn** [comment]
I am having the same issue. I did have to manually create the directory: 
/.local/share/WebTS/

Even afterwards I got the issue and no Log folder. 

I can also verify that I do have complete admin access read/write on my system including my user folder.

**Comment by andreifilip123** [comment]
Check out #601 
It's the same problem.

**Comment by Tanya0609** [comment]
Hi @CodeBroJohn, 

1. just double check, when you mentioned you created `/.local/share/WebTS/`, did you mean `/Users/[username]/.local/share/WebTS/ `?

2. after you manually created the directory, have you tried restart the VS code and run the extension again?

**Comment by Tanya0609** [comment]
Those are the steps to resolve this issue (copied from steps in #601):

1. Do you see any logs in the folder "/Users/[username]/.local/share/WebTS/Logs"? Could you share them?

Edited: it should be %LocalAppData%\WebTS\Logs, the one i shared was for Mac


2. /Users/[username]/.local/share/WebTS/ is the folder where templates are synchronized. Does your user have write permissions on /Users/[username]/.local/share?

3. If you have the permission, you could create the folder manually. `mkdir -p ~/.local/share/WebTS` and restart VS Code. 

Then it should work for you. Please let me know if you have any more question!

**Comment by CodeBroJohn** [comment]
> Hi @CodeBroJohn,
> 
> 1. just double check, when you mentioned you created `/.local/share/WebTS/`, did you mean `/Users/[username]/.local/share/WebTS/ `?
> 2. after you manually created the directory, have you tried restart the VS code and run the extension again?

@Tanya0609 

Yes I did mean that. Manually creating the directory there did not fix the issue for me. 

However, 
Going to the following path and changing permissions of the 0.0.19229.1 folder did.

C:\Users\[username]\AppData\Local\WebTS\Templates\Dev\Web\Any\0.0.19229.1

I think this is the likely culprit for most people reporting this issue.

**Comment by Tanya0609** [comment]
> > Hi @CodeBroJohn,
> > 
> > 1. just double check, when you mentioned you created `/.local/share/WebTS/`, did you mean `/Users/[username]/.local/share/WebTS/ `?
> > 2. after you manually created the directory, have you tried restart the VS code and run the extension again?
> 
> @Tanya0609
> 
> Yes I did mean that. Manually creating the directory there did not fix the issue for me.
> 
> However,
> Going to the following path and changing permissions of the 0.0.19229.1 folder did.
> 
> C:\Users[username]\AppData\Local\WebTS\Templates\Dev\Web\Any\0.0.19229.1
> 
> I think this is the likely culprit for most people reporting this issue.

Thanks for pointing out and sharing 👍

**Comment by sibille** [comment]
Is this still an issue? 
	
Were missing permissions on 
	
```
Mac: /Users/[username]/.local/share
Linux: //home/[username]/.local/share
Windows:  %LocalAppData%
```
	
the underlying reason or did you have to change anything else?
	
Opened issue https://github.com/microsoft/WebTemplateStudio/issues/1182 to improve user feedback.

**Comment by dgomezc** [comment]
We have published a new version of Web Template Studio that fix some errors with template synchronization. Error management has also been improved to include more info.

If you have template synchronization problems again, please opened a new issue.
