### ISSUE TITLE
Include Cosmos Node SDK when Cosmos is added to project

### ISSUE THREAD

**Issue by jasmingoh** [Microsoft/WebTemplateStudio#1134]
@markjbrown reached out and suggested to include Cosmos Node SDK as a part of the packages in the project when Cosmos is added in the project, `npm install @azure/cosmos`

**Comment by SahilTara** [comment]
In the generated code? Do we need to modify anything else? If not its a quick add. I think we do this for sql api, but not mongo let me recheck.

**Comment by SahilTara** [comment]
Yeah looking at how we did sql, we would need to change some stuff i would mark this as todo after summer.

**Comment by markjbrown** [comment]
Thanks @jasmingoh for creating this.

For Mongo you'd want to pull in their native Node.js driver.
npm install mongodb --save

Also note the connection string for MongoDB clients is also different. something like this,

mongodb://my-mongodb:26wA1hJzASD5s4EU4B2PFVOJ3Q92np63oTpnZacRiXmAfMPIsnmFsm4SO1W3cprXm1SPGCSzCoX2KbggnNJkHw==@my-mongodb.documents.azure.com:10255/?ssl=true&replicaSet=globaldb

Thanks.

**Comment by dgomezc** [comment]
Hi @markjbrown,

we already include @azure/cosmos library for CosmosDB SQL API, and MongoDB Node.js Driver and Mongoose library for CosmosDB MongoDB API.

To see this configuration, you have to add a List Page which is the sample to connect to CosmosDB.

We think we should include the libraries and connection code when adding CosmosDB Feature always, independently from the List Page.

What do you think about this aproach?

**Comment by markjbrown** [comment]
Hi David. I think that sounds ok. Could you post a screen cap of what that might look like? Just want to get a feel for it.

Thanks.

**Comment by dgomezc** [comment]
When adding CosmosDB Feature with MongoDB API, we think to include mongoConnect.js file that is in charge of creating the connection: 

![image](https://user-images.githubusercontent.com/12777039/69430413-dbc88200-0d35-11ea-9388-71a01a892583.png)

If adding CosmosDB with SQL API, we think to include sqlClient.js:

![image](https://user-images.githubusercontent.com/12777039/69430572-3661de00-0d36-11ea-81ff-3c65b8c84bf1.png)

**Comment by markjbrown** [comment]
Yes, ok. Looks good. Thanks David!

**Comment by sibille** [comment]
Verified in dev-nightly,
Templates version: 0.0.19339.1
Wizard version: 0.0.1933901
