### ISSUE TITLE
Should we ever have a peer to peer video + audio streaming page?

### ISSUE THREAD

**Issue by SahilTara** [Microsoft/WebTemplateStudio#1139]
What I mean by this is through the continued development of things like WebRTC, do you think we should support it in the extension at some point in the future? If so I will modify the issue to 
"Add peer to peer streaming page". Right now I'm playing around with WebRTC for a side project so I was just wondering if we'd ever want to add it to the extension as well.

What I mean is peer to peer video + audio streaming of course. Kind of like a mini conference call. Of course we would make it that by default, and probably document how to make it so only one person can stream and such. This feature could also tie in with auth 😄.

Let me know what you think @jasmingoh @jsondoo @njindal239 @ali-kha

**Comment by smmatte** [comment]
Not at this time,  as this opens up new compliance, legal requirements and security issues
