### ISSUE TITLE
Add close button on the "Creating Your Project" modal

### ISSUE THREAD

**Issue by denniswanjiru** [Microsoft/WebTemplateStudio#1140]
- Modal lacks close/exit button. Normally users click close(X) button or click outside the modal to exit the process.

**Comment by vsaroopchand** [comment]
Create new project essentially resets the UI; however, a close button is needed. I spent some time looking at the implementation. Should close simply reroute to ROUTES.NEW_PROJECT? Let me know and I will send a PR.

**Comment by jsondoo** [comment]
@xtinah-w any thoughts on the user flow here?

**Comment by Tanya0609** [comment]
@DennisWanjiru Thank you so much for the feedback! 

Could you elaborate a little more on the behavior of the close/exit button you would expect? Do you want it to show up so that you can reset the UI and start a new project? Or you just want to use it to close the modal?

**Comment by denniswanjiru** [comment]
<img width="1162" alt="Screenshot 2019-08-24 at 11 03 01" src="https://user-images.githubusercontent.com/22371596/63634506-156aed80-c660-11e9-8d7f-bee41b97247d.png">

Hello @Tanya0609 as a normal user I'd expect when I click anywhere outside the modal, the modal to close. Alternatively, we should have an (X) button as shown in the above image to have the same behavior.

@vsaroopchand I have seen that behavior but sometimes the user might not want to create a new project. Therefore, we need a way to close the modal or exit from the extension for better UX.

@jsondoo I'd suggest having an (X) button as shown in the image above but of white color, of course. This would give the user a clearer idea or more options of what to do next after scaffolding a new project.

**Comment by sibille** [comment]
@DennisWanjiru, agree we should add a close button, it feels weird, to not have one on a modal. 
Now, question is where should you go when hitting the close button?
Options: 
1. Close the whole wizard: This feels a bit heavy, also generation failed and you hit the close button with the intention to start over, you would have to relaunch the wizard.
2. Close the modal and stay on the generation summary page: Problem I see here is that this would allow to re-generate the same project, this could potentially lead to an inconsistent generation. 
3. Close the modal and go to the "Create new project" page: This would be the same behavior as hitting the "Create New Project" button.

Are there any other option you see? We think option 3 is the best choice. 
Also, the close button should only be enabled once generation has finished.

**Comment by sibille** [comment]
Verified in dev-nightly: 

Templates version: 0.1.20028.1
Wizard version: 0.1.2002801
