### ISSUE TITLE
Error while loading extension

### ISSUE THREAD

**Issue by PiotrekPKP** [Microsoft/WebTemplateStudio#1141]
Repro steps:

1.
2.

Action: Sync-Engine
Error type: Error
Error Message: Could not sync to template repository

Version: 0.0.1922901
OS: win32
VS Code Version: 1.37.1

<details>
<summary>Call Stack</summary>

```
LaunchExperience.<anonymous> (C:/Users/<user>/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.0.1922901/out/launchExperience.js:40:23)
Generator.next (<anonymous>)
fulfilled (C:/Users/PeterPkp123/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.0.1922901/out/launchExperience.js:4:58)
```

</details>

**Comment by Tanya0609** [comment]
Hi @PiotrekPKP, Thank you so much for reporting it!

Those are the steps to resolve this issue (same issue as #601):
**1. Do you see any logs in the folder "/Users/[username]/.local/share/WebTS/Logs"? Could you share them?** (it is a hidden file on Mac, not sure about win32)
Edited: the path is %LocalAppData%\WebTs\Logs for windows


**2. /Users/[username]/.local/share/WebTS/ is the folder where templates are synchronized. Does your user have write permissions on /Users/[username]/.local/share?**

3. If you have the permission, you could create the folder manually. `mkdir -p ~/.local/share/WebTS` and restart VS Code. 

Then it should work for you. Please let me know if you have any more question!

**Comment by SahilTara** [comment]
The file location sbould be %LocalAppData%\WebTs\Logs for windows let us know if its a permissions issue since that is what one user reported.

**Comment by sibille** [comment]
Is this still an issue? 
	
Were missing permissions on 
	
```
Mac: /Users/[username]/.local/share
Linux: //home/[username]/.local/share
Windows:  %LocalAppData%
```
	
the underlying reason or did you have to change anything else?
	
Opened issue https://github.com/microsoft/WebTemplateStudio/issues/1182 to improve user feedback.

**Comment by PiotrekPKP** [comment]
I will check that :) thanks for help

czw., 19 wrz 2019, 15:27 użytkownik sibille <notifications@github.com>
napisał:

**Comment by dgomezc** [comment]
We have published a new version of Web Template Studio that fix some errors with template synchronization. Error management has also been improved to include more info.

If you have template synchronization problems again, please opened a new issue.
