### ISSUE TITLE
Self-Hosted

### ISSUE THREAD

**Issue by dgleba** [Microsoft/WebTemplateStudio#1142]
Has anyone extended the generated app and self-hosted rather than use Azure? I wonder if that would be a huge job?

**Comment by Tanya0609** [comment]
We take the generated project, build it (npm install and npm run build) or (yarn install and yarn build), then grab the built project and deploy it to Azure App Service.

If you have a generated project, depends on how you want to self-hosted it, you may need or may not need to build it, then you could self-hosted too. Hope this helps :)

**Comment by sibille** [comment]
We're working on redefining the project structure on #1209, would love to hear your point of view.
