### ISSUE TITLE
Cannot find module 'eslint-config-react-app'

### ISSUE THREAD

**Issue by TimGaither** [Microsoft/WebTemplateStudio#1144]
I just want to run the generated app to see what it looks like but I continually get the error.

Does anyone know what needs to be done to fix the problem?

Thank you.

**Comment by Tanya0609** [comment]
Could you explain how you did it so that we can reproduce? Usually you would need to do "**npm install**" then "**npm start**" to start the generated app.

Also, have you checked out the README.md, there are instructions to run your generated app. It may help solve this error.

**Comment by sibille** [comment]
Is this still an issue? Can you share the generated project or steps to reproduce?

**Comment by sibille** [comment]
Closing this, please reopen if this still happens
