### ISSUE TITLE
Getting error creating app with Master Detail page

### ISSUE THREAD

**Issue by cesar128** [Microsoft/WebTemplateStudio#1148]
Im using Ubuntu18.04 all packages updated.

> node10.16.3
> Templates version: 0.0.19229.1
> Wizard version: 0.0.1922901

Vue.js
Flask
when i create and app and select Master Detail page it fails saying Templates could not be generated.

![Screenshot from 2019-08-23 23-02-40](https://user-images.githubusercontent.com/8787121/63631820-54feee80-c5fa-11e9-96ec-6a1cdc247e46.png)

**Comment by Tanya0609** [comment]
Hi @cesar128, thank you so much for reporting this issue! We will investigate this issue and come back to you!

**Comment by SahilTara** [comment]
I feel like it has to do with composition order. If you can check it out @Tanya0609 that would be great. If not, I can look into it in a few hours!

**Comment by SahilTara** [comment]
Hey @cesar128, thanks for the issue report. We found the source of the problem. Should be fine next update. Will ping you on this issue once its live in the production version of the extension!

**Comment by cesar128** [comment]
> Hey @cesar128, thanks for the issue report. We found the source of the problem. Should be fine next update. Will ping you on this issue once its live in the production version of the extension!

Thanks @SahilTara for your quick response! im glad i had a chance to contribute to this amazing project!
