### ISSUE TITLE
Extension will not launch

### ISSUE THREAD

**Issue by dangus21** [Microsoft/WebTemplateStudio#1155]
Repro steps:

1.
2.

Action: Sync-Engine
Error type: Error
Error Message: Could not sync to template repository

Version: 0.0.1922901
OS: win32
VS Code Version: 1.37.1

<details>
<summary>Call Stack</summary>

```
LaunchExperience.<anonymous> (c:/Users/<user>/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.0.1922901/out/launchExperience.js:40:23)
Generator.next (<anonymous>)
fulfilled (c:/Users/mmferreira/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.0.1922901/out/launchExperience.js:4:58)
```

</details>

**Comment by Tanya0609** [comment]
Hi @dangus21, thank you so much for reporting this issue!

Those are the steps to resolve this issue (same issue as #601):
1. Do you see any logs in the folder "/Users/[username]/.local/share/WebTS/Logs"? Could you share them? (it is a hidden file on Mac, not sure about win32)


2. /Users/[username]/.local/share/WebTS/ is the folder where templates are synchronized. Does your user have write permissions on /Users/[username]/.local/share?

3. If you have the permission, you could create the folder manually. `mkdir -p ~/.local/share/WebTS` and restart VS Code. 

Then it should work for you. Please let me know if you have any more question!

**Comment by SahilTara** [comment]
> Hi @dangus21, thank you so much for reporting this issue!
> 
> Those are the steps to resolve this issue (same issue as #601):
> 
> 1. Do you see any logs in the folder "/Users/[username]/.local/share/WebTS/Logs"? Could you share them? (it is a hidden file on Mac, not sure about win32)

Should be %LocalAppData%\WebTS\Logs

**Comment by CodeBroJohn** [comment]
@SahilTara thanks! 

That is the proper location. In my case there was a permissions issue in a deeply nested folder C:\Users\[username]\AppData\Local\WebTS\Templates\Dev\Web\Any\0.0.19229.1_tmp can't be rename. I changed permissions for folder 0.0.19229.1 and it fixed the issue.

**Comment by Tanya0609** [comment]
We are glad it works for you now! 

We will close this issue.
