### ISSUE TITLE
Add Http Interceptor for Angular

### ISSUE THREAD

**Issue by Tanya0609** [Microsoft/WebTemplateStudio#1159]
This is a sub issue from #1123, based on @mhatvan and @traore-i suggestion, we are splitting 1123 into sub issues so that it is more convenient for contribution and PR cross reference.

Introduce Http interceptor and use it in all the potential places in the generated angular code ( there are 4 page templates in total, a PR should address all of them.) You just have to set it up once, and it's a hook that will listen on.

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.0.19337.1
Wizard version: 0.0.1933701
