### ISSUE TITLE
Feedback on generated server side code

### ISSUE THREAD

**Issue by Tanya0609** [Microsoft/WebTemplateStudio#1160]
This is a sub issue from feedback on generated angular project #1123. In the feedback, there are few are related to the server side code.

## Server related code

- [ ] buildScript.js 

- Put a comment at the top explaining what this script is for, since this is a file added by us for App Service deployment. People may be confused why angular-cli is not being used 

- [ ] Package.json

- Don't use nodemon, you don't want that to go to production 
- Take out nodemon completely and just use node 
- Right now nodemon is a devDependencies, this may break things when it's deployed

**Comment by mcmxcdev** [comment]
@Tanya0609 what are the reasons for having a `buildScript.js`? Tell me what I should write as comment and then I will work on this ;)

**Comment by mcmxcdev** [comment]
Additionally, I would suggest adding e.g.  
```
"engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  }
```
to the package.json, to be clear about what versions of node and npm are supported by this project.

**Comment by sibille** [comment]
@mhatvan, the buildScript.js is used to compile the frontend Angular app and move the output to the server folder for later deployment.
