### ISSUE TITLE
Problem with open/close state in right bar when navigate

### ISSUE THREAD

**Issue by jasmingoh** [Microsoft/WebTemplateStudio#1162]
https://github.com/microsoft/WebTemplateStudio/pull/1136#issuecomment-524755600 and https://github.com/microsoft/WebTemplateStudio/pull/1136#issuecomment-525923107

> If you have more than one page. Then close the right side bar, the right sidebar should be user controlled and remain closed no matter what happens. Until we reach the summary page. However when going back to the first step then the pages step we have the sidebar open. This is because the state is local and on the first step there is no right sidebar. We will have to move the user controlled state to the redux state or something.

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.0.19329.1
Wizard version: 0.0.1932901
