### ISSUE TITLE
Angular Template: use async pipe rather than subscribe

### ISSUE THREAD

**Issue by RichardC64** [Microsoft/WebTemplateStudio#1163]
In MasterDetail, List and Grid pages in Angular templates, you subscribe to services (and no unsubscription in onDestroy).

It's better to use async pipe for that which manage unsubscription for you.
Could be something like this in MaterGrid page:

`
currentMasterDetailText: IMasterDetailText;
masterDetailText$: Observable<IMasterDetailText[]> =
 this.masterDetailService.getMasterDetailItems().pipe(
      catchError((error) => {
        this.WarningMessageOpen = true;
        this.WarningMessageText = 'Request to get master detail text failed: ${error}';
        return of(null);
      })
    );`

**Comment by RichardC64** [comment]
And no more needs to implement OnInit() interface

**Comment by sibille** [comment]
Added async pipes in PR https://github.com/microsoft/WebTemplateStudio/pull/1228
We still use OnInit to get data and select the initial value.

**Comment by sibille** [comment]
@RichardC64, we will use async pipes from Web Template Studio Version 0.1 onwards, you can see a sample of what's generated at https://github.com/sibille/angularNodeSampleApp. Would love to get your feedback.

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.0.19338.2
Wizard version: 0.0.1933802
