### ISSUE TITLE
Angular Template MasterDetail: use object for  masterDetailSidebarTab

### ISSUE THREAD

**Issue by RichardC64** [Microsoft/WebTemplateStudio#1164]
4 @Input() are used in MasterDetailSidebarTabComponent. I think it's the responsability to this component to choose what to show. So I would be better if there is only one @Input(), the IMasterDetailText object.

With this, in sidebar item, we can change the UI with no impact on container. (for example if there is more properties in MasterDetailText object).

Doing so, we can change the @Output() like:

@Output() displayTabClick = new EventEmitter<IMasterDetailText>(); // i would prefer itemClick ;-)

**Comment by Tanya0609** [comment]
Thanks for the great feedback!

**Comment by sibille** [comment]
We've also changed MasterDetailText to SampleOrder + a few other names on the MasterDetail page.

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.0.19338.2
Wizard version: 0.0.1933802
