### ISSUE TITLE
How to test templates modifications?

### ISSUE THREAD

**Issue by RichardC64** [Microsoft/WebTemplateStudio#1165]
Is there an easy way to test modifications in templates? I want to modify Anglura templates and see if modifications produce good generation.

I saw that templates are embedded in a zip file (Web.Any.Templates.mstx).

**Comment by Tanya0609** [comment]
Hi @RichardC64, the way to modify generated angular templates is from the code under /templates, [here](https://github.com/microsoft/WebTemplateStudio/wiki/Templates) is the link to our GitHub wiki. It is a more detailed document about how to do it.

To test the generated angular code, you will [start the extension](https://github.com/microsoft/WebTemplateStudio/wiki/Getting-Started) on your branch, and generate an angular project to see if it successfully generates one and open the project to check if the code has modified.

If you would love to contribute, please feel free to look at the [contribution guidelines](https://github.com/microsoft/WebTemplateStudio/blob/dev/CONTRIBUTING.md).

Hope this answers your question and please let me know if you would like to know more 👍

**Comment by sibille** [comment]
Docs for contributing on WebTS have been moved to https://github.com/microsoft/WebTemplateStudio/tree/dev/docs/contributing.
Closing this issue, please reopen if there are further questions.
