### ISSUE TITLE
only react template available

### ISSUE THREAD

**Issue by tommck** [Microsoft/WebTemplateStudio#1170]
When I run the web template studio, I only get the option for a React front end. No other options are shown :(

UPDATE: This is on the "wasteamaccount.webtemplatestudio-dev-nightly" extension

**Comment by jasmingoh** [comment]
@tommck, can you tell us the version number? It is located on the bottom of the right sidebar (under "Report an Issue")

**Comment by tommck** [comment]
The version I'm seeing is 0.0.1922901

@jasmingoh sorry for the delay

**Comment by sibille** [comment]
@tommck, that's the latest version, you should see Angular and Vue on this version too. 
Does this only happen on the frontendframeworks or for backend frameworks too? You should see Node and Flask there. 
Not sure how this can happen, a corrupt template folder could be the reason, what the OS your using?

**Comment by tommck** [comment]
@sibille I only have 1 choice for both.  only React/Node as options.

I uninstalled and reinstalled it too.  Is there anything else I can try?

**Comment by SahilTara** [comment]
Hmm something may be cached weird. Would you mind zipping your .templateengine folder and WebTs folders and then deleting the original folders? Should be located at ~/ or %UserProfile% and ~/local/.share or %LocalAppData% respectively. Then try uninstalling the extension, followed by reinstalling the extension. If this works please send us a copy of the zipped folders!

**Comment by tommck** [comment]
So, deleting those folders, uninstalling and reinstalling didn't help.

As far as OS goes, here's the "Help->About" info

![image](https://user-images.githubusercontent.com/981957/64477518-83d4a300-d16a-11e9-99d9-390ef055f404.png)

**Comment by tommck** [comment]
If I load the dev tools as soon as I launch VS Code, I see this:

[WASTeamAccount.WebTemplateStudio-dev-nightly]: Command `webTemplateStudioExtension.wizardLaunch` appears multiple times in the `commands` section.

**Comment by tommck** [comment]
oh weird... I apparently had 2 versions installed (?):

* Web Template Studio (staging-weekly)
wasteamaccount.webtemplatestudio-dev-nightly
* Web Template Studio
microsoft.webtemplatestudio

I'm betting that could have had something to do with it :)

**Comment by tommck** [comment]
Yep!  That fixed it!  I uninstalled both and then reinstalled the staging-weekly.

(I may have built/installed the other one myself from source a long time ago and forgot)

**Comment by tommck** [comment]
Thanks so much for the help, folks.  I'm up and running fine now :)
