### ISSUE TITLE
ASP.Net core backend

### ISSUE THREAD

**Issue by steskalja** [Microsoft/WebTemplateStudio#1175]
Are there any plans to support ASP.Net Core as the backend? This would be useful since a number of people would like to use C#.

**Comment by jcoc611-microsoft** [comment]
Thank you for your suggestion! We are tracking ASP.Net support on issue #200 . We currently do not have a concrete plan/timeline for this but it is definitely in our backlog. Thank you again.

If you'd like to add more info or request updates, please do so in the linked issue!
