### ISSUE TITLE
Error: Could not sync to template repository

### ISSUE THREAD

**Issue by vikasrana07** [Microsoft/WebTemplateStudio#1178]
Repro steps:

1. Tried to open WebTemplateStudio got below error

Action: Sync-Engine
Error type: Error
Error Message: Could not sync to template repository

Version: 0.0.1925201
OS: win32
VS Code Version: 1.38.1

<details>
<summary>Call Stack</summary>

```
LaunchExperience.<anonymous> (c:/Users/<user>/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.0.1925201/out/launchExperience.js:40:23)
Generator.next (<anonymous>)
fulfilled (c:/Users/vikas.rana/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.0.1925201/out/launchExperience.js:4:58)
```

</details>

**Comment by AndreMaz** [comment]
Hey @vikasrana87 
Did you check the https://github.com/microsoft/WebTemplateStudio/issues/1125 and https://github.com/microsoft/WebTemplateStudio/issues/1132 ? I think it's the same issue

**Comment by sibille** [comment]
Is this still an issue? 
	
Were missing permissions on 
	
```
Mac: /Users/[username]/.local/share
Linux: //home/[username]/.local/share
Windows:  %LocalAppData%
```
	
the underlying reason or did you have to change anything else?
	
Opened issue https://github.com/microsoft/WebTemplateStudio/issues/1182 to improve user feedback.

**Comment by dgomezc** [comment]
We have published a new version of Web Template Studio that fix some errors with template synchronization. Error management has also been improved to include more info.

If you have template synchronization problems again, please opened a new issue.
