### ISSUE TITLE
Environment variables not populated in .env

### ISSUE THREAD

**Issue by henryjw** [Microsoft/WebTemplateStudio#1187]
Using React + Node.js with MongoDB flavor of Cosmos db.

Below is what my `.env` file looks like. Even though a database was successfully created and deployed, the configuration was not updated.

```shell
Web Template Studio will automatically add Cosmos Keys to this file once your database has been deployed.
To manually retrieve your Cosmos database connection string and keys, follow these docs (https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-mongoose)

COSMOSDB_CONNSTR=mongodb://{cosmos-user}.documents.azure.com:10255/{dbname}
COSMOSDB_USER=cosmos-user
COSMOSDB_PASSWORD=cosmos-secret
```

**Comment by sibille** [comment]
Thanks for reporting! We'll have a look at it.

**Comment by dgomezc** [comment]
Hi @henryjw,

The creation of the CosmosDB service in Azure takes some time and Web Template Studio waits for it to finish.When the creation is finished, Web Template Studio displays a notification asking if you want to replace the CosmosDB connection string in the .env file. 

Did Web Template Studio show the notification of the replacement of the connection string and did you have click the "Yes" button?

![image](https://user-images.githubusercontent.com/12777039/65768511-72f7cb80-e131-11e9-90fd-d705d2631b50.png)

**Comment by henryjw** [comment]
Thanks for the pointer @dgomezc. I didn't see it when setting up my project, but I'll set up another one to see if it pops up.

**Comment by AndreMaz** [comment]
@henryjw I've also had an impression that something went wrong when WebTS was creating CosmosDB instance. It took around 2 minutes to show the popup that @dgomezc is referring to. But in the end it worked well.

**Comment by henryjw** [comment]
I created a new project and can confirm that the popup appeared. The `.env` file was populated as expected.
