### ISSUE TITLE
[Wizard] Cosmos Options Inconsistencies

### ISSUE THREAD

**Issue by AndreMaz** [Microsoft/WebTemplateStudio#1190]
While trying to integrate CosmosDB with Moleculer https://github.com/microsoft/WebTemplateStudio/issues/1124#issuecomment-535908869 I've noticed some inconsistencies:

Subscription is showing repeatedly "Free Trial" but I only have one (free) account.
![image](https://user-images.githubusercontent.com/9802754/65835946-9747d980-e2e4-11e9-9611-5b6a05dac3cf.png)

In API section I'm getting two options (Mongo and SQL). I'm currently working only on Mongo integration so SQL should not appear in options. I think some kind of check and validation should be done here.
![image](https://user-images.githubusercontent.com/9802754/65835967-d24a0d00-e2e4-11e9-95f4-e02a2a83c547.png)

**Comment by dgomezc** [comment]
Hi @AndreMaz,

Web Template Studio has an internal dependency on the Azure Account extension, that provides Azure Subscription data. Can you execute "Azure: Select Subscriptions" command in VSCode and confirm that show the same subscriptions?

In API section, we can select MongoDB or SQL because this options are selectables when create a MongoDB services in Azure Portal, and some users prefer SQL instead of MongoDB.

**Comment by AndreMaz** [comment]
Hi @dgomezc 

This is what I get when I run "Azure: Select Subscriptions"
![image](https://user-images.githubusercontent.com/9802754/65893909-ba37c380-e3a0-11e9-9154-18e0df907211.png)

> some users prefer SQL instead of MongoDB.

I absolutely agree with you. But what I'm trying to say is that, at this moment, Moleculer does not support Cosmos SQL API. There is no composition template for that. So the presence of SQL gives a wrong impression to the end user.

Same might happen with other frameworks that will be added in the future.  For example, imagine that after a while you decide to add support for Cassandra (one of several APIs supported by Azure). What would happen then? Will you update all back-end frameworks at the same time? If no, then the same situation would happen: the combination "framework X + Cassandra" would appear as a valid option to the end user. Even if framework X does not support Cassandra.

So I think that CosmosDB API selection field should only show a set of valid options, i.e.,  APIs that the selected framework (Step 2) has support.

**Comment by dgomezc** [comment]
Hi @AndreMaz, 

I could not reproduce the problem, but when reviewing the code, I have seen that it can be related to azure sessions. To fix this, I will verify that you cannot add a subscription to the combobox if one with the same Id already exists.

Regarding the CosmosDB API selection, we think Web Template Studio should only show services available for selected Framework.

We have created the #1194 issue to fix this.

That said, fixing this will take some time. Can you add CosmosDB with SQL API for MoleculerJS?

**Comment by AndreMaz** [comment]
Hi @dgomezc 

>I could not reproduce the problem, but when reviewing the code, I have seen that it can be related to azure sessions. To fix this, I will verify that you cannot add a subscription to the combobox if one with the same Id already exists.

That's great. If you need some additional info (logs or something) just let me know.

>That said, fixing this will take some time. Can you add CosmosDB with SQL API for MoleculerJS?

Yes, that's the next thing that I'm going to do. However, integration with SQL API will take a little bit more time. I'll have to look at `@azure/cosmos` lib and extend Moleculer's DB adapter to work with it.
I'll update https://github.com/microsoft/WebTemplateStudio/issues/1124 as I progress.
