### ISSUE TITLE
command 'webTemplateStudioExtension.wizardLaunch' not found

### ISSUE THREAD

**Issue by umdstu** [Microsoft/WebTemplateStudio#1191]
After installing the latest via the latest `vsix` file, the Launch command does not work.

The error in the popup, as the title indicates, is `command 'webTemplateStudioExtension.wizardLaunch' not found`. The only _Output_ I see related to the extension is in the _Log (Shared)_ section which states: 
```
...
[info] Installation completed. wasteamaccount.webtemplatestudio-dev-nightly
[warning] Cannot install dependencies of extension:
wasteamaccount.webtemplatestudio-dev-nightly
[info] Successfully installed the extension:
wasteamaccount.webtemplatestudio-dev-nightly
```

**Comment by dgomezc** [comment]
Hi @umdstu,

- which version did you try to install?
- Did you get the vsix from the marketplace?

Web Template Studio installs the following dependencies:
- Azure Account
- Azure App Service

Where those extensions installed sucessfully?

**Comment by umdstu** [comment]
@dgomezc good morning
The version is 0.0.1925201, yes it's from the market place- but no I didn't install the other two VSIX files first. It would be really cool if these could be optional (somehow) as I take it they only apply to the `Deploy` part, and we won't be using the Azure portion- just the building part, not deploying. Anyway to get the dependencies listed on the [INSTALL](https://github.com/microsoft/WebTemplateStudio/blob/dev/docs/install.md) doc either way for manual install section?

That said, after installing those two `vsix` files, then re-installing this extension, it seems to have started up!


Edit: Nevermind, just noticed #1192 !

**Comment by ladipo** [comment]
I am still having problem launching the wizard, I keep getting this message "command 'webTemplateStudioExtension.wizardLaunch' not found"

Even when all dependencies are installed.

I am using version 0.1.1934601

**Comment by sibille** [comment]
Hi @ladipo, thanks for reporting. 
Could you share the output from Log (Shared) and Log (Extension Host) to see whats the underlying reason?

**Comment by ladipo** [comment]
I reinstall VS code and it is working fine.

Thanks for the response

Ladipo
