### ISSUE TITLE
Dynamically show azure services based on selected framework and project type

### ISSUE THREAD

**Issue by dgomezc** [Microsoft/WebTemplateStudio#1194]
Currently, when we develop a new Backend Framework, but not yet  have implemented CosmosDB Service integration, Web Template Studio shows the CosmosDB box in Services page. If you select CosmosDB service and create an app, the database is created but not integrated into the app.

We should only show Services that are available for selected Frameworks and ProjectType,

**Comment by sibille** [comment]
Verified in dev-nighlty: 
Templates version: 0.3.20189.2
Wizard version: 0.3.2018902
