### ISSUE TITLE
Fresh React/Node app does not redirect at root when served from App Service

### ISSUE THREAD

**Issue by nickwalkmsft** [Microsoft/WebTemplateStudio#1198]
**Repro**:

1. Use WebTS to create a new Node/React app with a single blank page and App Service. Open the project when finished.
2. *Optional, to illustrate scope of problem*: Open the terminal, do `npm install`, `npm run-script build`, `npm start`. Note that browsing to both localhost:3000 and localhost:3001, with no path, cause the browser to redirect to /Blank, which is the desired behavior.
3. Run `Web Template Studio: Deploy App` and wait for deployment to finish.
4. Click "Browse Website" in the notification that appears and wait for the browser to load.

**Expected**: Browser is redirected to /Blank.

**Actual**: Empty page, no redirect. Adding `/<anything here>` to the URL loads /Blank but does not update the URL in the address bar.

**Comment by sibille** [comment]
@nickwalkmsft, thanks for reporting!
We could reproduce the issue and are investigating the root cause.

**Comment by dgomezc** [comment]
Hi @nickwalkmsft, 

We believe there is a problem with React redirection and to correct it you have to make changes to the App.jsx file.

Replace this:

```xml
<Redirect exact path = "/" to = "/Blank" /> 
```

with this:

```xml
<Route exact path = "/">
  <Redirect to="/Blank" />
</Route>
```
 
and Re-Deploy your app.

We continue to investigate to detect the specific problem.
