### ISSUE TITLE
Django intigration

### ISSUE THREAD

**Issue by raj1rana** [Microsoft/WebTemplateStudio#1200]
Hi Team, 

I am impressed with the worked you have done it is amazing, and the choreography that you have created with your coding is indeed something to look up to.

It is really good that you have added flask as a Backend but as a Django developer i would love to work with your creation + Django frame work.

thank you.

**Comment by dgomezc** [comment]
Thanks for your feedback, adding Django is already on our backlog (https://github.com/microsoft/WebTemplateStudio/issues/195).
