### ISSUE TITLE
ENOENT: no such file or directory, stat '/home/site/wwwroot/build/index.html' after deployed React/Node webapp generated by WebTS

### ISSUE THREAD

**Issue by diamondseaturtle** [Microsoft/WebTemplateStudio#1203]
Created a webapp with WebTS (React+Node, 4 pages - blank, grid, list and master_details), did configure optional azure web server and cosmosDB (mongodb), after I successfully deployed the generated webapp to Azure **from my local machine using "Web Template Studio: Deploy App",** I got error : ENOENT: no such file or directory, stat '/home/site/wwwroot/build/index.html' when accessing my website. 

SSH to the VM in Azure, it seemed that only the back-end was deployed, please see the output below, is this a bug or did I miss anything? please help. 
===========================================================
root@84540f7db5ec:/home/site/wwwroot# pwd
/home/site/wwwroot
root@84540f7db5ec:/home/site/wwwroot# ls -al
total 1958
drwxrwxrwx 2 nobody nogroup    4096 Oct 17 00:10 .
drwxrwxrwx 2 nobody nogroup       0 Oct 16 23:58 ..
-rwxrwxrwx 1 nobody nogroup    1248 Oct 16 23:42 app.js
-rwxrwxrwx 1 nobody nogroup     329 Oct 16 23:43 constants.js
drwxrwxrwx 2 nobody nogroup       0 Oct 16 23:58 mongo
lrwxrwxrwx 1 nobody nogroup      13 Oct 17 00:10 node_modules -> /node_modules
-rwxrwxrwx 1 nobody nogroup 1957362 Oct 17 00:09 node_modules.tar.gz
-rwxrwxrwx 1 nobody nogroup      86 Oct 17 00:09 oryx-manifest.toml
-rwxrwxrwx 1 nobody nogroup   21619 Oct 16 23:58 package-lock.json
-rwxrwxrwx 1 nobody nogroup     433 Oct 16 23:42 package.json
drwxrwxrwx 2 nobody nogroup       0 Oct 16 23:58 routes
-rwxrwxrwx 1 nobody nogroup    3608 Oct 16 23:43 sampleData.js
-rwxrwxrwx 1 nobody nogroup    1731 Oct 16 23:42 server.js

**Comment by sibille** [comment]
@diamondseaturtle, I wasn't able to reproduce this. Could you send us the logs from the deploy command? Also what does your local project folder look like after running the deploy command?

**Comment by dgomezc** [comment]
We have improved feedback when deploying the app. Please, reopen with more info if this still happens to you.
