### ISSUE TITLE
Differences in output between executing "Deploy App" and executing npm locally

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1206]
Underlying issue for https://github.com/microsoft/WebTemplateStudio/issues/1198 is that the build output created by running "npm install" and "npm build" locally or through the Deploy App are different. 
		
When executing through the DeployApp command the sources for path-to-regexp points to `"../node_modules/path-to-regexp/index.js".` which results in issue https://github.com/ReactTraining/react-router/issues/6840
		
When executing the commands "npm install" and "npm build" locally it points to 	`"../node_modules/react-router/node_modules/path-to-regexp/index.js"` .

**Comment by manvydasu** [comment]
There is clearly something wrong. Similiar issue was menitoned there https://github.com/ReactTraining/react-router/issues/6840

And the solution was to manually install regexp???? Does not seem ok.

**Comment by sibille** [comment]
This issue should be solved with the reorganized project structure.
