### ISSUE TITLE
Angular styling improvements

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1215]
Following up from issue https://github.com/microsoft/WebTemplateStudio/issues/1123 to attack the remaining points: 

Apply the following improvements for angular styles: 

- [x] Make the arrays all one liners (smaller is better) in all ts code
- [x] @Injectable({}) should be one line
- [x] Review and fix tslint issues
- [x] Fix: tslint and prettier not working in /AngularDefault/src/app/app-shell folder
- [x] folder is called /AngularJS which can be confusing since it is the naming convention for Angular 1
- [x] Add title to buttons and images
- [x] double check the way we import svgs

**Comment by sibille** [comment]
@johnpapa, this issue was created based on feedback you gave to the interns working on WebTS. All changes are applied now and you can see what we generate from Web Template Studio Version 0.1 onwards at https://github.com/sibille/angularNodeSampleApp . Would love to get your feedback!

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.0.19338.2
Wizard version: 0.0.1933802
