### ISSUE TITLE
Add home page to generated project

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1216]
Following up from issue https://github.com/microsoft/WebTemplateStudio/issues/1123.

First page in wizard should be treated as "Home page".

This should be done in : 
- [x] React
- [x] Angular
- [x] Vue

We should use the Layout.json in the .template.config folder to configure the home page in the templates

**Comment by sibille** [comment]
@johnpapa, this issue was created based on feedback you gave to the interns working on WebTS. All changes are applied now and you can see what we generate from Web Template Studio Version 0.1 onwards at https://github.com/sibille/angularNodeSampleApp . Would love to get your feedback!

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.0.19337.1
Wizard version: 0.0.1933701
