### ISSUE TITLE
Update sql_client.py when Azure SDK for Python v4 be released 

### ISSUE THREAD

**Issue by dgomezc** [Microsoft/WebTemplateStudio#1224]
When Azure SDK for Python v4 is officially launched, we have to update the sql_client.py file to use the new create_database_if_not_exists and create_container_if_not_exists methods, to control the creation of the database and the container without using the proposed try catch in issue #1217

**Comment by prupipho** [comment]
#1595  Not doing this update as part of this on the following PR #1657 
Take into account that we are also doing this task #1618 on this Milestone 0.6

**Comment by prupipho** [comment]
Tested on nightly version.

Templates version: 0.3.21050.1
Wizard version: 0.3.2105001
