### ISSUE TITLE
 componentdidmount deprecated - update version

### ISSUE THREAD

**Issue by Pfurr** [Microsoft/WebTemplateStudio#1232]
Is it possible to update this extension to the new ReactJS features? For example, componentdidmount is deprecated ( see --> list.js component)

**Comment by JamesSingleton** [comment]
When did `componentDidMount()` become deprecated? Looks like it isn't https://reactjs.org/docs/react-component.html#componentdidmount

**Comment by Pfurr** [comment]
> When did `componentDidMount()` become deprecated? Looks like it isn't https://reactjs.org/docs/react-component.html#componentdidmount

See docs about useEffect

**Comment by JamesSingleton** [comment]
`useEffect` is just a hook that you can think of as  `componentDidMount`, `componentDidUpdate`, and `componentWillUnmount` combined to be used only in a functional component. I don't see in https://reactjs.org/docs/hooks-reference.html?no-cache=1#useeffect or https://reactjs.org/docs/hooks-effect.html saying that `componentDidMount` is deprecated. You can't use `useEffect` in a class based component and I don't think class based components are going to be deprecated anytime soon.

**Comment by Pfurr** [comment]
You can write the same code using the hook, writing less code ect ect

**Comment by SahilTara** [comment]
Hey @pherm what you're suggesting is a great idea. In fact we had discussed adding hooks to our project back in march and again around july. I think what you're actually suggesting is to have an option for functional or class components. Since componentDidMount isn't deprecated, it's just what you would use for class based components.

**Comment by JamesSingleton** [comment]
@SahilTara yeah having an option sure, but you cannot replace `componentDidMount` with `useEffect`

**Comment by SahilTara** [comment]
@JamesSingleton that is correct since they are used in two different contexts.

**Comment by Pfurr** [comment]
> Hey @pherm what you're suggesting is a great idea. In fact we had discussed adding hooks to our project back in march and again around july. I think what you're actually suggesting is to have an option for functional or class components. Since componentDidMount isn't deprecated, it's just what you would use for class based components.

Hooks are only needed to write react classes component as functional components with state. so, you can rewrite all as  functional components + hooks.

**Comment by JamesSingleton** [comment]
There would have to be another step in setting up a project though and ask if they want functional components with state. Not everyone wants them or can use them.

**Comment by sibille** [comment]
Giving the choice to the developer would duplicate the page templates for react +  
looking at react docs hooks seem to be the recommended choice for new projects.

We think we should refactor our react templates to use hooks.

**Comment by sibille** [comment]
A generated react app with hooks will look like this: 
[reactHooksSampleApp.zip](https://github.com/microsoft/WebTemplateStudio/files/4126907/reactHooksSampleApp.zip)

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.1.20055.2
Wizard version: 0.1.2005502
