### ISSUE TITLE
Changes in Master detail page

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1242]
Suggestions:

- Provide different images for different companies:
Right now sample data service returns the same image for each company, to make the sample more realistic, we should  return different images (located in the public image folder) and use the  greyAvatar.svg as fallback image
	
- Remove the breadcrumb
	Not sure why this was added in the first place, as it redirects to the same page.

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.0.19337.1
Wizard version: 0.0.1933701
