### ISSUE TITLE
Update libraries to latest version in Angular templates

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1258]
We should use fixed library versions in dependencies to avoid issues like https://github.com/microsoft/WebTemplateStudio/issues/1282

**Comment by duongleh** [comment]
Angular 9 is out now. Any plan to update to the latest version?

**Comment by sibille** [comment]
Yes, we're looking into updating angular to the latest version

**Comment by sibille** [comment]
Verified on dev-nighlty:
Templates version: 0.1.20056.1
Wizard version: 0.1.2005601
