### ISSUE TITLE
Update libraries to latest version in node templates

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1259]
We should use fixed library versions in dependencies to avoid issues like https://github.com/microsoft/WebTemplateStudio/issues/1282

**Comment by sibille** [comment]
Update to package azure/cosmos 3.5.2 requires code changes due to breaking changes.

**Comment by dgomezc** [comment]
Verified in dev-nightly ;
Templates version: 0.1.20052.2
Wizard version: 0.1.2005202
