### ISSUE TITLE
Update libraries to latest version in Moleculer templates

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1262]
Check if libraries in moleculer are up to date and update if there is anything new

**Comment by sibille** [comment]
@andremaz, we've seen moleculer has released version 0.14 with a lot of new stuff last week. we'd love to update the templates to the latest version, could you help here?

**Comment by AndreMaz** [comment]
Sure thing @sibille . I've created a PR (https://github.com/microsoft/WebTemplateStudio/pull/1346) with the latest version

**Comment by sibille** [comment]
Awesome! Thanks!

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.1.20055.2
Wizard version: 0.1.2005502
