### ISSUE TITLE
Change page addition and removal behavior

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1264]
We should apply the following changes to the page addition and removal behaviour to make it clearer that pages should be given a custom name:

- After adding a page the focus should move to the right side bar to edit the item name
- Remove the minus button as it's not very clear which page will be removed + Items can be removed from the right side bar
- The whole card should be clickable
- Move the add icon to the top of the box and show only onhover, to make clear that the whole box is clickable

**Comment by dgomezc** [comment]
Outstanding work:

- The focus doesn´t move to the page name textbox when adding a page.
- Card border should be more bold when adding a page.
- Plus icon on card should show when card is focused.
- The detail link should be clickable when is focused and press space or enter keys.

**Comment by dgomezc** [comment]
Outstanding work:

- When adding page, the focus should go to the page name textbox in right panel.
- The card border should be more bold when adding pages.
- The read more link should be clickable when is focused and press space or enter keys.
- The plus icon on card should show when card is focused.

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.1.20058.2
Wizard version: 0.1.2005802
