### ISSUE TITLE
Fix lint test on angular, react and vue templates 

### ISSUE THREAD

**Issue by javieraparisivaldes** [Microsoft/WebTemplateStudio#1274]
- [x] Fix lint test on angular.
- [x] Add lint test on react templates:
run "npm i --save eslint" + add in package.json
"lint": "eslint src/**/*.js src/**/*.jsx"
"eslint-plugin-react": "^7.17.0",
- [x] Fix lint test vue.
- [x] Run lint in template tests

**Execute**
run "npm run lint"

**Comment by sibille** [comment]
Verified on dev-nightly; 
Templates version: 0.1.20056.1
Wizard version: 0.1.2005601
