### ISSUE TITLE
MS Edge with react dont work

### ISSUE THREAD

**Issue by javieraparisivaldes** [Microsoft/WebTemplateStudio#1282]
**Describe the bug**
When loaded into the browser, it throws a syntax error to the console on this line:
webpackHotDevClient line 60
// Connect to WebpackDevServer via a socket.
var connection = new WebSocket(

**To Reproduce**
Choose React + Node on WebTS
On generated code console run "npm i" + "npm start"

**Comment by sibille** [comment]
Underlying issue is https://github.com/facebook/create-react-app/issues/8084

**Comment by sibille** [comment]
Verified in version 
Templates version: 0.1.19345.1
Wizard version: 0.1.1934501
