### ISSUE TITLE
Improve performance using chunks on react project (wizard)

### ISSUE THREAD

**Issue by javieraparisivaldes** [Microsoft/WebTemplateStudio#1301]
**Describe the bug**
On the react code (Wizard) use react.lazy on optional components

**To Reproduce**
When mount the component App.jsx the optional components always load:

**Expected behavior**
All the optional components on will be load by react.lazy

**Screenshots**
![image](https://user-images.githubusercontent.com/56872233/71181449-74d6b400-2274-11ea-913c-f5eb85842bb6.png)

![image](https://user-images.githubusercontent.com/56872233/71181512-93d54600-2274-11ea-8f20-ffc39af7b85c.png)

**Comment by dgomezc** [comment]
Verified in dev branch.
