### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by HaythamAmairah** [Microsoft/WebTemplateStudio#1317]
- Issue Type: `Performance`
- Extension Name: `WebTemplateStudio-dev-nightly`
- Extension Version: `0.1.1934601`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.41.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\user\WASTeamAccount.WebTemplateStudio-dev-nightly-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by sibille** [comment]
Thanks for reporting!
Could you attach the file C:\Users\user\WASTeamAccount.WebTemplateStudio-dev-nightly-unresponsive.cpuprofile.txt to diagnose what caused the issue? Also, did you get this issue when starting Web Template Studio, while navigating through the wizard or on project generation?

**Comment by HaythamAmairah** [comment]
I got this issue on project generation!
The file is attached.
Thanks!

[WASTeamAccount.WebTemplateStudio-dev-nightly-unresponsive.cpuprofile.txt](https://github.com/microsoft/WebTemplateStudio/files/4108091/WASTeamAccount.WebTemplateStudio-dev-nightly-unresponsive.cpuprofile.txt)

**Comment by sibille** [comment]
Moving to 0.3 as this needs some refactoring first

**Comment by sibille** [comment]
We've optimized CoreTS build output #1340 and improve performance using chunks on react project (wizard) #1301. Moving to 0.4 to finish this work by bundling extension files.

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.3.20189.2
Wizard version: 0.3.2018902
