### ISSUE TITLE
Resource location defaults to Central US

### ISSUE THREAD

**Issue by MethodicalMadness** [Microsoft/WebTemplateStudio#1320]
I made an React app with mongo db. All went well and was quite impressed until I realised the location was Central US. It would be ideal to have an option when adding resources to choose resource locations or add already available resources.

**Comment by sibille** [comment]
Thanks for your feedback! We're thinking of providing an advanced mode for Cosmos DB and App Service configuration, to give the possibility to configure the location and resource group. Are there any other values that you'd like to personalize?

**Comment by MethodicalMadness** [comment]
I am only just starting out on my web app journey with Azure, so I will refrain from giving advice on things I do not know. What I do know is the location of resources cannot be changed through the azure portal, once created that is where it is. My suggestion would be to focus on configuration options that are immutable first.

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.2.20122.1
Wizard version: 0.2.2012201
