### ISSUE TITLE
 Cannot start generation engine. spawn UNKNOWN

### ISSUE THREAD

**Issue by ajaymagan** [Microsoft/WebTemplateStudio#1327]
Repro steps:

1.
2.

Action: Sync-Engine
Error type: UNKNOWN
Error Message: Cannot start generation engine. spawn UNKNOWN

Version: 0.1.1934601
OS: win32
VS Code Version: 1.41.1

<details>
<summary>Call Stack</summary>

```
ChildProcess.spawn (internal/child_process.js:394:11)
Object.spawn (child_process.js:548:9)
Function.<anonymous> (c:/Users/<user>/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.1.1934601/out/coreTemplateStudio.js:54:55)
Generator.next (<anonymous>)
c:/Users/Ajay Magan/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.1.1934601/out/coreTemplateStudio.js:7:71
new Promise (<anonymous>)
__awaiter (c:/Users/Ajay Magan/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.1.1934601/out/coreTemplateStudio.js:3:12)
Function.GetInstance (c:/Users/Ajay Magan/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.1.1934601/out/coreTemplateStudio.js:31:16)
LaunchExperience.<anonymous> (c:/Users/Ajay Magan/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.1.1934601/out/launchExperience.js:21:59)
Generator.next (<anonymous>)
c:/Users/Ajay Magan/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.1.1934601/out/launchExperience.js:7:71
new Promise (<anonymous>)
__awaiter (c:/Users/Ajay Magan/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.1.1934601/out/launchExperience.js:3:12)
LaunchExperience.launchApiSyncModule (c:/Users/Ajay Magan/.vs

**Comment by sibille** [comment]
Thanks for reporting @ajaymagan. 
Could you provide us your log from C:\Users\[username]\.vscode\extensions\wasteamaccount.webtemplatestudio-dev-nightly-0.1.1934601\logs 
and check if your user has execution permissions on C:\Users\[username]\.vscode\extensions\wasteamaccount.webtemplatestudio-dev-nightly-0.1.1934601\src\corets-cli\win32?

**Comment by ajaymagan** [comment]
Hi attached log as requested

**Comment by sibille** [comment]
Hi @ajaymagan, it seems that the file has not made it through to github with the email response, could you attach it on the github thread?

**Comment by ajaymagan** [comment]
[wts.log](https://github.com/microsoft/WebTemplateStudio/files/4139884/wts.log)

**Comment by sibille** [comment]
Thanks for sharing! 
The problem seems to be that the generation engine executable cannot be started. 
Could you confirm if the file C:\Users\[username]\.vscode\extensions\wasteamaccount.webtemplatestudio-dev-nightly-0.1.2003401\src\corets-cli\win32\Microsoft.Templates.Cli.exe exists and you have execution permissions on it?

**Comment by sibille** [comment]
Closing this, please reopen if this is still an issue.
