### ISSUE TITLE
App Service Name should not be re-calculated when changing the subscription

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1338]
**Describe the bug**
App Service Name should not be re-calculated when changing the subscription.

**To Reproduce**
1. Launch Web Template Studio
2. Click next until reaching the Add optional cloud services page
3. Click "Add to my project"
4. Choose a subscription.
5. Enter a custom web app name that is unique.
6. Choose a different subscription

=> The selected name

**Expected behavior**
The name should not be changed

**Comment by dgomezc** [comment]
this was resolved in https://github.com/microsoft/WebTemplateStudio/pull/1377

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.2.20122.1
Wizard version: 0.2.2012201
