### ISSUE TITLE
Remove redirect popup

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1339]
Right now there are two popups shown when you click on a link. 
We should remove our popup as Visual Studio Code has a built in message. 

![image](https://user-images.githubusercontent.com/24698018/74720885-c7adf700-5236-11ea-888b-6705cafb2819.png)
![image](https://user-images.githubusercontent.com/24698018/74720902-d399b900-5236-11ea-8b01-201aef0d977c.png)

**Comment by javieraparisivaldes** [comment]
Verified in dev-nightly:
Templates version: 0.2.20119.2
Wizard version: 0.2.2011902
