### ISSUE TITLE
Replace component names in templates

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1341]
We should replace the component and file names in the templates with the name the user chose. 
For example if a user adds a master detail page called Contacts, "MasterDetail" should be replaced by "Contacts" in all files.

Generated code should be: 
![image](https://user-images.githubusercontent.com/24698018/74727769-f4b3d700-5241-11ea-9839-9a2f2ced32cd.png)

or 
![image](https://user-images.githubusercontent.com/24698018/74729564-ef0bc080-5244-11ea-8abb-a7aab00e068b.png)

instead of: 
![image](https://user-images.githubusercontent.com/24698018/74729266-7a388680-5244-11ea-9db6-02ed5c77b517.png)

This applies to all frontend frameworks.

**Comment by javieraparisivaldes** [comment]
Verified in dev-nightly:
Templates version: 0.2.20119.2
Wizard version: 0.2.2011902
