### ISSUE TITLE
dev-nightly: Error when cancel project path selection

### ISSUE THREAD

**Issue by dgomezc** [Microsoft/WebTemplateStudio#1349]
In the start page, when you click on the browse button a modal is shown to select a new path. If you press on the cancel button, the textbox shows the old path, but really the path is empty. If you go to the next page, in the right panel, the location section is empty, and if you go back to starting page, the textbox is empty. 

Generating project failed too.

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.1.20058.2
Wizard version: 0.1.2005802
