### ISSUE TITLE
Review redux store

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1355]
Review state properties in redux store and decide which properties to remove / refactor

This issue split on the following issues:
- Review vscode redux store #1398 
- Refactor GenerationStatus property on redux store #1400 
- Refactor DependencyInfo property on redux store #1402 
- Refactor templates and config property on redux store #1409
- Refactor userSelection property on redux store #1412
- Refactor navigation property on redux store #1416
- Refactor redux-thunk to redux-saga on redux store #1414
- Refactor services property on redux store #1417

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.2.20119.2
Wizard version: 0.2.2011902
