### ISSUE TITLE
Reorganize actions/reducers/selectors folders

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1356]
Goal is to have actions/reducers and selectors for a specific state property (f.ex. userSelection) closer to each other.

Change folder structure to a structure like this:
 - src/store/selection/frameworks/action.ts
 -  src/store/selection/frameworks/model.ts
 -  src/store/selection/frameworks/reducer.ts
 -  src/store/selection/frameworks/selector.ts

Actions:
  - Change names (we should only use set (+ add and delete for lists)
  - Delete actions that are not used
  - Delete actions that compute state that can be retrieven from select
  - Check that all function names finish with the word 'action'

**Comment by javieraparisivaldes** [comment]
Verified in dev-nightly:
Templates version: 0.2.20119.2
Wizard version: 0.2.2011902
