### ISSUE TITLE
Images should be read from templates folder

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1376]
We should read the images from the templates folder (through the extension) instead of having them duplicated on the client.

For example, the node image should come from https://github.com/microsoft/WebTemplateStudio/blob/dev/templates/Web/_catalog/backendframeworks/Node.svg

**Comment by prupipho** [comment]
Updated images that now comes from the templates folder:
- frontend & backend framework
- pages
- azure services

**Comment by prupipho** [comment]
Checked on nightly version:

Templates version: 0.3.20287.1
Wizard version: 0.3.2028701
