### ISSUE TITLE
Fix warnings on test execution

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1403]
Execution of tests on client print warnings saying; 

` It looks like you're using a version of react-dom that supports the "act" function, but not an awaitable version of "act" which you will need. Please upgrade to at least react-dom@16.9.0 to remove this warning.
`

We should update react-dom. Looking into this requires to remove react-loadable (which uses deprecated ComponentWillMount) and replace with loadable-components or react-lazy

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.3.20189.2
Wizard version: 0.3.2018902
