### ISSUE TITLE
Refactor AzureServices Page

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1404]
Changes to be done in step 4 (Add Optional Cloud Services) page:
- [x] Rename AzureLoginModal to AzureServicesModal
- [x] Add the possibility to sign in (add sign in link where user details and sign out are now (top right of main page))

**Comment by sibille** [comment]
Updating the original issue as part of this was done in other issues. Opened separate issues (#1577, #1578, #1579) for things that need more investigation or discussion first.

**Comment by prupipho** [comment]
still to check and implement: 
- accessibility: should access Sign Out link with tabs

**Comment by prupipho** [comment]
Checked on nightly version:

Templates version: 0.3.20287.1
Wizard version: 0.3.2028701
