### ISSUE TITLE
Refactor templates and config property on redux store

### ISSUE THREAD

**Issue by javieraparisivaldes** [Microsoft/WebTemplateStudio#1409]
Create templates and config property on redux store with:
- (templates) frontendFrameworks, backendFrameworks and Pages
- (config) detailsPage, previewStatus, validations, isValidatingName, versions and azureProfileData.

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.2.20119.2
Wizard version: 0.2.2011902
