### ISSUE TITLE
Refactor redux-saga to redux store

### ISSUE THREAD

**Issue by javieraparisivaldes** [Microsoft/WebTemplateStudio#1414]
Refactor redux-thunk to redux-saga on redux store:
- Change redux-thunk by redux-saga
- Create saga subscriptions on frameworks selection, load framework list, load user login, load templates
- Remove following packages @types/react-router-dom @types/react-router
- Fix generation modal when create web without azure hosting

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.2.20119.2
Wizard version: 0.2.2011902
