### ISSUE TITLE
Refactor navigation property on redux store

### ISSUE THREAD

**Issue by javieraparisivaldes** [Microsoft/WebTemplateStudio#1416]
Refactor navigation property on redux store
- Modals & Router
- Refactor type keys on (azure, template, config, navigation and userSelection)
- Refactor /store/ActionType
- Delete unused and repeat action, selector, interfaces and reducers

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.2.20119.2
Wizard version: 0.2.2011902
