### ISSUE TITLE
Web Template Studio: Launch crachs

### ISSUE THREAD

**Issue by Fuadk** [Microsoft/WebTemplateStudio#1432]
Repro steps:

1.
2.

Action: Sync-Engine
Error type: UNKNOWN
Error Message: Cannot start generation engine. spawn UNKNOWN

Version: 0.2.2007701
OS: win32
VS Code Version: 1.44.2

<details>
<summary>Call Stack</summary>

```
ChildProcess.spawn (internal/child_process.js:394:11)
Object.spawn (child_process.js:553:9)
Function.<anonymous> (c:/Users/<user>/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.2.2007701/out/coreTemplateStudio.js:53:55)
Generator.next (<anonymous>)
c:/Users/FuadK/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.2.2007701/out/coreTemplateStudio.js:7:71
new Promise (<anonymous>)
__awaiter (c:/Users/FuadK/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.2.2007701/out/coreTemplateStudio.js:3:12)
Function.GetInstance (c:/Users/FuadK/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.2.2007701/out/coreTemplateStudio.js:31:16)
LaunchExperience.<anonymous> (c:/Users/FuadK/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.2.2007701/out/launchExperience.js:21:59)
Generator.next (<anonymous>)
c:/Users/FuadK/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.2.2007701/out/launchExperience.js:7:71
new Promise (<anonymous>)
__awaiter (c:/Users/FuadK/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.2.2007701/out/launchExperience.js:3:12)
LaunchExperience.launchApiSyncModule (c:/Users/FuadK/.vscode/extensions/wasteamaccount.webtemplatestu

**Comment by sibille** [comment]
Hi @Fyadk, the problem seems to be that the generation engine executable cannot be started.
Could you confirm if the file C:\Users\[username]\.vscode\extensions\wasteamaccount.webtemplatestudio-dev-nightly-0.2.2007701\src\corets-cli\win32\Microsoft.Templates.Cli.exe exists and you have execution permissions on it?

**Comment by Fuadk** [comment]
Hello,
The file exists, but it seems to be a 64 bit, and I am running windows7 32
bit cause I am getting a message stating to check 64 bit or 32 bit, when I
try to run the program.
Regards,
Fuad

**Comment by prupipho** [comment]
Sorry this got forgotten @Fuadk , let us know if it happens again. Closing the issue but do not hesitate contacting us again if this is still an issue.
