### ISSUE TITLE
Remove Quickstart and always show right side bar and generate button instead

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1445]
Telemetry has shown that Quickstart button hasn't a big usage (around 10%) and half of the people that use the QuickStart button edit the project before generation to add in more pages or azure services. 
We should change the wizard to always show the right side bar with project information and enable the generation button from the first step to allow people to generate whenever they feel everything is ready.

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.3.20189.2
Wizard version: 0.3.2018902
