### ISSUE TITLE
Remove add pages / reset pages button from right side bar on summary page

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1447]
Telemetry has shown that both buttons are not used frequently (4% and 1%)
- Add pages buttons usage is 4%, but pages can be added using the AddPages page with a better user experience (change page name once added).
- Reset pages usage is only 1%, pages can be deleted one by one.

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.3.20189.2
Wizard version: 0.3.2018902
