### ISSUE TITLE
Review wizard styles

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1448]
We should review wizard styles to match VS Code styles and reduce size of texts and controls.

**Comment by prupipho** [comment]
Review https://github.com/microsoft/WebTemplateStudio/pull/1687#issuecomment-745334470
Styles in the Project Type Area:
- Card: padding of the description text
- Detail Page: missing screenshot image & Licences links

**Comment by prupipho** [comment]
We thought about removing the arrow in the Next button on the bottom right.

![image](https://user-images.githubusercontent.com/1333036/102910694-3e310c00-447b-11eb-8f7d-e265c42afb45.png)

**Comment by prupipho** [comment]
Also remove this **>** from this link as it will redirect to the website and doesn´t seem useful

![image](https://user-images.githubusercontent.com/1333036/104198097-1d2e5c00-5426-11eb-944a-1dbe57651b8a.png)

**Comment by prupipho** [comment]
Ready for review. Probably something else would appear. Still small things to do but I think it would be good you review that now.

**Missing:** 
- Orange border on focus  
     - on Dragabble Page on rightside bar 
     - Services modal. App Name 
- Probably change Create New Project Button on last modal to blue style 
 -Review position of page counter in PageCard

**Comment by sibille** [comment]
Verified on nightly build: 
Templates version: 0.3.21078.1
Wizard version: 0.3.2107801
