### ISSUE TITLE
Right side bar overlaps scroll when collapsed

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1458]
Repro steps: 
1. Launch Web Template Studio
2. Go to second page
3. Collapse right side bar

=> Scroll is hidden by collapsed right side bar

Scrollbar visible:
![image](https://user-images.githubusercontent.com/24698018/82425219-8112a780-9a86-11ea-8ba4-9f29f909faa0.png)

Scrollbar hidden:
![image](https://user-images.githubusercontent.com/24698018/82425283-97b8fe80-9a86-11ea-98a6-d1c82660d69d.png)

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.3.20189.2
Wizard version: 0.3.2018902
