### ISSUE TITLE
Error when compiling client

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1474]
Regarding the error, this is the output of `./build-client.sh`
![image](https://user-images.githubusercontent.com/9802754/84029250-ff79af80-a989-11ea-9d77-bf2007b896ca.png)

_Originally posted by @AndreMaz in https://github.com/microsoft/WebTemplateStudio/issues/1469#issuecomment-640567829_

**Comment by sibille** [comment]
@AndreMaz, opened a new issue for this. What node version are you using? There seems to be an issue on node 13.13 https://github.com/nodejs/node/issues/32852

**Comment by AndreMaz** [comment]
@sibille I'm using `v12.17`

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.3.20189.2
Wizard version: 0.3.2018902
