### ISSUE TITLE
Licenses from composition templates are not shown

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1479]
The licenses modal only shows licenses from selected templates. Licenses from composition templates (as for example from the Cosmos DB templates for Mongo or SQL) are not shown.
We should add a command to the Cli to get all licenses to be able to show all licenses.

**Comment by sibille** [comment]
To make GetAllLicences work correctly all licences used in a template have to be added to the wts.lincenses tag on the template.json, currently this is only done for the bootrap license.

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.3.20189.2
Wizard version: 0.3.2018902
