### ISSUE TITLE
Dev-nightly: Invalid project name allows to navigate and generate project

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1484]
**Describe the bug**
Invalid project name allows to navigate and generate project

**To Reproduce**
1. Start Web Template Studio
2. Set the project name to something invalid (f. ex leave it empty)
3. Click next

=> Generate button is enabled

**Expected behavior**
You should not be able to leave the first page while the project name is not valid.

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.3.20189.2
Wizard version: 0.3.2018902
