### ISSUE TITLE
Throw exceptions on extension log on cli comunications

### ISSUE THREAD

**Issue by javieraparisivaldes** [Microsoft/WebTemplateStudio#1498]
Throw exceptions on extension log on cli comunications

On src/extension/src/coreTemplateStudio.ts, in the function readStream (line 100) the callback of 'process.stdout' should write a exception on log when dont found a valid id response

**Comment by javieraparisivaldes** [comment]
Now the extension write fine the exception on log when id call is wrong, attach on log pic with id call wrong

![throwexception1](https://user-images.githubusercontent.com/56872233/90981686-c7cedc80-e562-11ea-8d8a-276f8128c7d6.png)

**Comment by prupipho** [comment]
Verified this while Debugging extension 
![image](https://user-images.githubusercontent.com/1333036/96989494-0adb0b00-1526-11eb-843e-717f1a59de17.png)
