### ISSUE TITLE
Cleanup parameters in templates

### ISSUE THREAD

**Issue by dgomezc** [Microsoft/WebTemplateStudio#1506]
The Param_RootNamespace parameter is unnecessary in most templates, they must be reviewed and removed from those that are not necessary.

**Comment by sibille** [comment]
In the project templates there are a bunch of unused parameters as username, etc too.

**Comment by prupipho** [comment]
Verified in nigthtly build:
Templates version: 0.3.20296.1
Wizard version: 0.3.2029601
