### ISSUE TITLE
Change project generation order

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1507]
There are currently 2 common project templates and 1 for each backend and frontend framework.
Naming of  frameworks determines the order of generation. This makes compositions complex as in some combinations frontend is generated before backend and viceversa. 
We should order project generation by wts.compositionOrder to establish a deterministic order: First common project template (1 should be sufficient),  then frontend framework project template, then backend framework projet template

**Comment by prupipho** [comment]
Reviewed.
