### ISSUE TITLE
Refactor navigation in Wizard

### ISSUE THREAD

**Issue by javieraparisivaldes** [Microsoft/WebTemplateStudio#1523]
Refactor navigation 
- Should read the routes depending on platform
- Each route should include all route and navigation related information on a single list (currently two)
- Refactor footer component to dynamically show back/next depending on the routes from route service.
- Reactor topNavBar component to use a singles route list
- Each object route in the list should have name, route, isVisited, isActive.

The order of request from client to extension should be:
```
const { platform } = getTemplateInfo () //"web"
const projectTypes = getProjectType(platform) //["FullStackWebApp"] 
const frameworks = getFrameworks(projectTypes[0]) //[React, Angular, Vue],[Node, Python, Moleculer, ASP.NET]
const pages = getPages(projectTypes[0], frontEndFramework, backEndFramework] //[wts.Page.React.Blank, wts.Page.React.List, wts.Page.React.MasterDetail, wts.Page.React.Grid
```

**Comment by prupipho** [comment]
@prupipho Next week have a look at adding new routes

**Comment by prupipho** [comment]
Review on dev version on 4th November
