### ISSUE TITLE
Make frontend/backend framework selection optional in Wizard depending on the projectType

### ISSUE THREAD

**Issue by javieraparisivaldes** [Microsoft/WebTemplateStudio#1524]
Make frontend/backend framework selection optional 

On load action, sagas, validations, conditions .... the app should allow optional frontend/backend selection depending on the project type.

**Comment by prupipho** [comment]
@prupipho  Next week have a look at adding new routes

**Comment by prupipho** [comment]
Complete the support for this issue:
- remove backend OR frontend from appearing on the page when not needed (filter from result from CLI)
   - [x] Frameworks Page.
   - [x] Rightsidebar.

- [x] getPages command should work just with -b or -f params. (client)
- [x] review routing for the navigation. (constants is the right place)
- [x] allow to generate even if only one type of framework has been selected.

**Comment by dgomezc** [comment]
Checked on nightly version:

Templates version: 0.3.21047.1
Wizard version: 0.3.2104701
