### ISSUE TITLE
Allow different entry points on extension to launch WebTS Wizard

### ISSUE THREAD

**Issue by dgomezc** [Microsoft/WebTemplateStudio#1529]
Allow different entry points on extension to launch WebTS Wizard.
The idea is that different entry points sync different template packages and launch the wizard with different configurations. 
 
Also adapt Client to work with different mocks when launched for development.

**Comment by prupipho** [comment]
Checked on nightly version:

Templates version: 0.3.20287.1
Wizard version: 0.3.2028701
