### ISSUE TITLE
Check conditions before executing  deploy app command 

### ISSUE THREAD

**Issue by dgomezc** [Microsoft/WebTemplateStudio#1530]
Validate if Visual Studio Code has a valid project open before executing the deployment command.

We should at least verify that there is a package.json with the install and build commands the command needs. It's probably a good idea to check if the project was generated by Web Template Studio, to avoid unexpected side effects.

**Comment by prupipho** [comment]
Checked on nightly version:

Templates version: 0.3.20287.1
Wizard version: 0.3.2028701
