### ISSUE TITLE
What's the meaning of: "front-end is served on http://localhost:3000/ and the back-end on http://localhost:3001/"

### ISSUE THREAD

**Issue by haohuancheng** [Microsoft/WebTemplateStudio#1539]
**What's the different of this?**

The front-end is served on http://localhost:3000/ and the back-end on http://localhost:3001/

**Comment by sibille** [comment]
@haohuancheng, not sure if I understand your question.

Web Template Studio is a VS Code extension that creates full stack web applications. 

> The front-end is served on http://localhost:3000/ and the back-end on http://localhost:3001/

This phrase is from the Readme.md file of a generated Web App. It states that the front-end part of the generated application in development served on port 3000, the backend part on port 3001. Does this answer your question? How can we make this clearer?

**Comment by haohuancheng** [comment]
Thank you very much for your reply.
I want to know why it is necessary to publish two ports? Is it OK to publish only one port? and How do I publish this app to azure web site?

**Comment by sibille** [comment]
The mentioned setup is for development. 
For deployment on Azure we have detailed instructions on https://github.com/microsoft/WebTemplateStudio/blob/dev/docs/generated-apps/deployment.md. 

Before publishing the frontend web app is built as a static web app in the build folder.  

We're planning to re-organize the Readme.md file of the generated app (#1505) and should explain this part with more detail.

**Comment by prupipho** [comment]
Thanks again for your feedback @haohuancheng .

We did the re-organization of the Readme.md of the generated apps. If you let us know what is the frameworks you currently use we can show you one example of a full readme file so you can have check if it clarifies your doubts about it.

We split the frontend and backend information in two different sections, so now it should be clearer to understand what those two localhost url mean. 

Find and example below with **React and Node** as an example:

![image](https://user-images.githubusercontent.com/1333036/95477656-e0ffe100-0988-11eb-8c10-2488ea6b3b0b.png)

**Comment by prupipho** [comment]
Verified on nightly build:
Templates version: 0.3.20287.1
Wizard version: 0.3.2028701
