### ISSUE TITLE
Update zipIgnorePattern in settings.json file to ignore correct files

### ISSUE THREAD

**Issue by javieraparisivaldes** [Microsoft/WebTemplateStudio#1549]
When deploy app VSCode show this message

![image](https://user-images.githubusercontent.com/56872233/87785096-e04b2900-c837-11ea-99cc-dd2b70e453ef.png)

Check how show by checking the file /.vscode/settings.json

**Comment by sibille** [comment]
Issue is that the zipIgnorePattern that is added to the settings.json in some conditions adds files and folders that should not be excluded (f.ex. the build folder). We should check if we can avoid this by adding the correct files to the zipIgnorePattern on generation.

**Comment by dgomezc** [comment]
Fixed with the new project structure (#1494)
