### ISSUE TITLE
Cannot makes new project

### ISSUE THREAD

**Issue by ktt9117** [Microsoft/WebTemplateStudio#1563]
Repro steps:

1. Run visual studio code, go to extension tab and install web template studio.
2. Select WebTS by pressing Shift + command + P as indicated in the guide.

Action: Sync-Engine
Error type: Error
Error Message: Could not sync to template repository. Details: Cannot call write after a stream was destroyed

Version: 0.4.2020202
OS: darwin
VS Code Version: 1.47.3

<details>
<summary>Call Stack</summary>

```
l.<anonymous> (/Users/<user>/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.4.2020202/dist/extension.js:488:3726057)
Generator.next (<anonymous>)
o (/Users/gradler/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.4.2020202/dist/extension.js:488:3724997)
```

</details>

**Comment by sibille** [comment]
Hi @ktt9117, 
could you share the wts.log file from /Users/<user>/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.4.2020202/logs to see what's the underlying reason?

**Comment by ktt9117** [comment]
@sibille here's my log file. thanks! 
[wts.log](https://github.com/microsoft/WebTemplateStudio/files/5013953/wts.log)

**Comment by sibille** [comment]
Thanks for sharing. Underlying issue seems to behttps://github.com/dotnet/runtime/issues/34793. Not sure we can do anything about this. Did you run any other memory consuming processes while executing WebTS? Did a restart help?

**Comment by sibille** [comment]
Closing this, please reopen if this is still an issue.
