### ISSUE TITLE
Microsoft.Web/serverfarms apiVersion value throws warning

### ISSUE THREAD

**Issue by evansmith1377** [Microsoft/WebTemplateStudio#1564]
**Problem**
For a project created with hosting in an Azure App Service, the arm-templates > web-app-template.json file has an invalid apiVersion value for the Microsoft.Web/serverfarms resource. The generated value of "2017-08-01" throws a warning:
Value is not accepted. Valid values: "2018-02-01"

[This page](https://docs.microsoft.com/en-us/azure/templates/microsoft.web/allversions) says the valid values are:
2019-08-01
2018-02-01
2016-09-01

**Reproduction Steps**
1. Create a new WebTS project with React, ASP.NET, App Service, and CosmosDB
2. View the web-app-template.json file
3. See the warning (I'm unsure what linter/extension produces the warning)

**Expected behavior**
I'd like to see the generated apiVersion is set to a valid value or a comment on this issue asserting that the generated value is actually acceptable.

**Screenshots**
![image](https://user-images.githubusercontent.com/26821065/89375465-4ac2ec80-d6b3-11ea-9663-1f1c193b9c04.png)

- **VS Code Version:** 
Version: 1.47.3 (user setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

- **WebTS Wizard Version:** 
Wizard version: 0.4.2020202

- **WebTS Template Version:** 
Templates version: 0.4.20202.2

- **OS:**
Windows 10, Version 1909, Build 18363.997

**Comment by sibille** [comment]
Thanks for reporting!

**Comment by prupipho** [comment]
Verified on nightly build:
Templates version: 0.3.20287.1
Wizard version: 0.3.2028701
