### ISSUE TITLE
ASP.NET + AppService + CosmosDB (SQL): settings keys differ between Azure App Service configuration and Startup.cs

### ISSUE THREAD

**Issue by evansmith1377** [Microsoft/WebTemplateStudio#1565]
In a newly created app with App Service and CosmosDB, the automatically created Azure App Service configuration has settings named:
- COSMOSDB_PRIMARY_KEY
- COSMOSDB_URI

When using ASP.NET backend, the generated server/Startup.cs file references settings named:
- CosmosDB.Account
- CosmosDB.Key
- CosmosDB.DatabaseName
- CosmosDB.ContainerName

The app works locally because it uses appsettings.json which has settings that match what Startup.cs references.
When using the WebTS Deploy to Web App function, the appsettings.json file gets deployed and used, so the app works remotely, too.

I think the generated application should use configuration settings with names that match what gets generated in the auto-created Azure App Service. If the setting names match, it will not matter that changes to appsettings.json get deployed.

From perusing the WebTS source code and searching for a duplicate issue, it appears that some backends use server\SQL\.env files like the one at the source code path below which reference setting names consistent with those generated in the Azure App Service. The generated ASP.NET backend does not contain .env files that I could find. The ASP.NET backend relies on the appsettings.json file alone.
`templates/Web/_composition/_shared/Feature.Azure.Cosmos.SQL.AddEnvFile/.env`

I thought this might be related to this issue, but I don't think ASP.NET uses .env files:
https://github.com/microsoft/WebTemplateStudio/issues/1187

**To Reproduce**
1. Create new React app with ASP.NET backend hosted in Azure App Service and a CosmosDB with SQL API
2. Compare the Azure App Service Settings > Configuration > Application Settings names to those in the server\appsettings.json and server\Startup.cs files
3. Note the differing setting names

**Expected behavior**
Names in appsettings.json and references to those settings throughout the backend should be consistent with those automatically added to the Azure App Service.

**Screenshots**
Default Settings Configuration in App Service
![image](https://user-images.githubusercontent.com/26821065/89714835-1d05ce00-d967-11ea-9d8f-cdf509956d4b.png)

appsettings.json
![image](https://user-images.githubusercontent.com/26821065/89714881-56d6d480-d967-11ea-9710-5d947da2a152.png)

server\Startup.cs
![image](https://user-images.githubusercontent.com/26821065/89714895-6b1ad180-d967-11ea-81cd-22405875440f.png)

**Additional context**
I discovered this while setting up CI/CD connected to GitHub. Since appsettings.json is added to .gitignore by default, and matching settings were not in the Azure App Service configuration for Application Settings, the app would not start after I deployed it (not using the WebTS Deploy to Web App feature). I was able to add matching settings in the Azure App Service and get the app to start.

The generated appsettings.json file uses nested settings names, which are referenced like CosmosDB.Account. Dot notation is not valid in the Azure App Service, so the period is replaced by a double underscore when adding to the Azure App Service settings like this: CosmosDB__Account

**System**

- **VS Code Version:** 
Version: 1.47.3 (user setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

- **WebTS Wizard Version:** 
Wizard version: 0.4.2020202

- **WebTS Template Version:** 
Templates version: 0.4.20202.2

- **OS:**
Windows 10, Version 1909, Build 18363.997

**Comment by sibille** [comment]
Great catch. We should adjust the keys in the app settings.json file.

**Comment by prupipho** [comment]
Thanks again for your feedback @evansmith1377 ,

We´ve worked on this issue and will be released on the next Release.

You can see now that settings names match in Startup.cs, appSettings.json and Azure App Service configuration for Application Settings.

Notice that due to [another issue](#1494 ) Startup.cs andappSettings.json would be under `backend` folder instead of `server`.

### Startup.cs
![image](https://user-images.githubusercontent.com/1333036/95478990-89627500-098a-11eb-986a-02c60f371d8a.png)

### appSettings.json
![image](https://user-images.githubusercontent.com/1333036/95479118-b1ea6f00-098a-11eb-98d9-827ae4f7bea6.png)

### Azure > App Services > Configuration >Application Configuration
![image](https://user-images.githubusercontent.com/1333036/95479283-e2320d80-098a-11eb-8b79-e2b7250aa4af.png)

**Comment by prupipho** [comment]
**Verified on nightly build:**

Templates version: 0.3.20282.1
Wizard version: 0.3.2028201
