### ISSUE TITLE
Move close button in right side bar to upper right corner

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1587]
The close button of the right side bar should be in the upper right corner (same place where the hamburger button is when opening the menu.

![image](https://user-images.githubusercontent.com/24698018/92216142-37fc2d00-ee96-11ea-8472-cc22fcbf84d3.png)
![image](https://user-images.githubusercontent.com/24698018/92216196-48aca300-ee96-11ea-8499-c452d6da80a0.png)

**Comment by prupipho** [comment]
Checked on nightly version:

Templates version: 0.3.20287.1
Wizard version: 0.3.2028701
