### ISSUE TITLE
Feedback on generated Python code

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1618]
We got the following feedback on the python code we generate and should adapt the code acordingly:

1. Why the module constants? There's only one file so why not keep it with the rest of the `server` code?
2. Why a dict? I would make them all global variables in the module (makes it easier for linters to tell you typed something wrong)
3. https://github.com/dgomezc/StructureProposalApp/blob/master/AngularFlask/backend/server.py#L57 should be using your constants
4. You mixed your import style: https://github.com/dgomezc/StructureProposalApp/blob/master/AngularFlask/backend/server.py#L3 imports a submodule while https://github.com/dgomezc/StructureProposalApp/blob/master/AngularFlask/backend/server.py#L1 is importing objects off of modules; choose a style and stick with it (and the right one is importing the module 😉
5. Why is https://github.com/dgomezc/StructureProposalApp/blob/master/AngularFlask/backend/server.py#L33 creating an entire list when all you care about is 0, 1, or more than 1 results?
6. https://github.com/dgomezc/StructureProposalApp/blob/master/AngularFlask/backend/server.py#L16 and https://github.com/dgomezc/StructureProposalApp/blob/master/AngularFlask/backend/server.py#L46 are the same function
7. Break https://github.com/dgomezc/StructureProposalApp/blob/master/AngularFlask/backend/server.py#L53 into an 'if' statement
8. Your imports are not following PEP 8; use isort or reorder_python_imports to fix that
9. You're missing docstrings
10. Style is inconsistent; I would run it through Black
11. The README's section on the server code layout is incorrect
12. Any reason the code isn't being made into a package if you're going to have multiple module that are all related to each other?
13. If this is a template than your requirements.txt file is too strict; either just require flask>=1.1.2,<2 or use something like pip-tools so people can update the dependencies easily later on their own

**Comment by sibille** [comment]
We'll rename the backend/src folder to the app name, as this is a better name for the main app package.

**Comment by prupipho** [comment]
Tested on nightly version.

Templates version: 0.3.21050.1
Wizard version: 0.3.2105001

We´ll check a couple of things on Monday together but seems ok. @sibille @dgomezc @prupipho

**Comment by prupipho** [comment]
Tested on nightly version:
Templates version: 0.3.21068.1
Wizard version: 0.3.2106801
