### ISSUE TITLE
Dev-nightly: Project Name and folder doesn´t validate correctly 

### ISSUE THREAD

**Issue by prupipho** [Microsoft/WebTemplateStudio#1624]
**Describe the bug**
Project Name and folder doesn´t validate correctly when changing the path. 
Related with #1582 

**To Reproduce**
1. Choose a folder in your PC where you want to save your generated Web Applications.
   - create a folder myApp on it or make sure it does exist already
1. Open Web Template Studio extension
   notice it chooses a name for you. For example: _myApp2_
1. Modify name to try to use the existing one you checked before. For example myApp
  it should show an error message saying that it already exists
1. Change the path to be in a folder that may allow you to create that _myApp_ project 
1. Change name to _myApp_ in there
1. Go back a level where it shouldn´t be allowed to create a project _myApp_ 
See that now it doesn´t display the error message.
1. Click button "**Create Project**"

**Expected behavior**
   If the directory already exists it shouldn´t allow you to create the project and should show an **error message**
   No matter if you change the **Project Name** or the **Project Path** it needs to validate that the selected name and folder are correct.

**Screenshots**

![image](https://user-images.githubusercontent.com/1333036/95324121-86d72100-089f-11eb-94ce-63455ad49409.png)
![image](https://user-images.githubusercontent.com/1333036/95324243-b9811980-089f-11eb-9d1a-e5df15c2796f.png)
![image](https://user-images.githubusercontent.com/1333036/95325317-50020a80-08a1-11eb-9d6c-2020e0e5d513.png)
![image](https://user-images.githubusercontent.com/1333036/95325532-a111fe80-08a1-11eb-8d52-58b9f7e248f9.png)

**Comment by sibille** [comment]
Verified in nightly version: 
Templates version: 0.3.20297.1
Wizard version: 0.3.2029701
