### ISSUE TITLE
Wrong path configured in extension configuration WTS: Change save to location does not display error message

### ISSUE THREAD

**Issue by prupipho** [Microsoft/WebTemplateStudio#1636]
**Describe the bug**
Wrong path doesn´t seem to show error message correctly.

**To Reproduce**
1. Configure a wrong path in the Extension Settings
1. Open Web Template Studio (Ctrl + Shift + P: Web Template Studio)
2. See that error message appears on the name of the project but it does not complain about the invalid path.

**Expected behavior**
It should show that the path it is not valid.

**Screenshots**
![image](https://user-images.githubusercontent.com/1333036/96605902-ffee6380-12f6-11eb-933e-fa90472053ca.png)

![image](https://user-images.githubusercontent.com/1333036/96603125-03342000-12f4-11eb-8728-0e69b84ff974.png)

**System**

- **WebTS Version:** 0.4

**Comment by sibille** [comment]
Verified in nightly version:
Templates version: 0.3.20311.1
Wizard version: 0.3.2031101
