### ISSUE TITLE
Dev-nightly: Change moleculer scripts 

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1656]
As mentioned in https://github.com/microsoft/WebTemplateStudio/pull/1651#issuecomment-718748708, we interchanged the moleculer start and start-dev commands during the project reorganization. 

Correct commands are: 
 ```
"scripts": {
    "start-dev": "moleculer-runner --repl --hot services",
    "start": "moleculer-runner services"
  },
```

**Comment by prupipho** [comment]
Reviewed in dev
