### ISSUE TITLE
Proposal: React Native Templates in Web Template Studio

### ISSUE THREAD

**Issue by JeanRoca** [Microsoft/WebTemplateStudio#1662]
# Proposal: React Native Templates in Web Template Studio

## Summary
In an effort to extend our templates to more platforms, WebTS should provide users with [React Native](https://github.com/microsoft/react-native-windows) templates for Windows. These templates should provide users with just enough code to get started building a RN app that works on Windows with an initial set of pages and design patterns.

## Rationale

* React Native for Windows allows you to use JavaScript to write native Windows apps that work on all Windows 10 devices **as well** as macOS desktop and laptop ecosystems.
* WebTS has a nice and user friendly wizard that is already integrated into VS Code which is one of the preferred editors for RN.

## Scope
| Capability | Priority |
| :---------- | :------- |
| Provide an easy way for users to create a RN app through the wizard | Must |
| Provide a separate entry point into the wizard for RN apps | Must |
| Allow users to install all RN [dependencies](https://microsoft.github.io/react-native-windows/docs/rnw-dependencies) from the extension  | Must |
| Have documentation for using these templates | Must |
| Provide at least one navigation pattern (ideally drawer or tab navigation) | Should |
| Provide users with at least the three pages as templating options (Blank, Master/Detail, Settings) | Should |

## Roadmap
* Create the mockups and deploy to dev nightly
* Get feedback from community and team and add enhancements
* Create templates
* Document templates
* CI/CD integration

**Comment by stmoy** [comment]
> React Native for Windows allows you to use JavaScript to write native Windows apps that work on all Windows 10 devices as well as macOS desktop and laptop ecosystems.

Put another way: React Native enables you to use JavaScript to write native apps across iOS, Android, and now Windows, and macOS as well. (The distinction is that React Native is the "root" product and React Native for Windows/macOS are extensions on that product.) WTS may start out just focusing on Windows apps, but I would suspect that a higher majority of people would want iOS/Android first and Windows/macOS as an add-in.

One open question would be the relationship between this and the [react-native CLI](https://github.com/react-native-community/cli) which is the current main way to create a new React Native app. Would this supersede it? Depend on it? Expand on it?

**Comment by asklar** [comment]
There are often breaking changes in RN/RNW across (minor) releases. The project templates and build infrastructure changes from version to version. We expect most people will be using a project that was generated with our CLI, so I'd be concerned about there being "yet another way to create a RNW app", and what the compatibility and migration story would be

**Comment by JeanRoca** [comment]
> > React Native for Windows allows you to use JavaScript to write native Windows apps that work on all Windows 10 devices as well as macOS desktop and laptop ecosystems.
> 
> Put another way: React Native enables you to use JavaScript to write native apps across iOS, Android, and now Windows, and macOS as well. (The distinction is that React Native is the "root" product and React Native for Windows/macOS are extensions on that product.) WTS may start out just focusing on Windows apps, but I would suspect that a higher majority of people would want iOS/Android first and Windows/macOS as an add-in.
> 
> One open question would be the relationship between this and the [react-native CLI](https://github.com/react-native-community/cli) which is the current main way to create a new React Native app. Would this supersede it? Depend on it? Expand on it?

I think the way we are looking at it would be to expand on the CLI. Our template generator would only depend on the CLI for initial template creation and we are certainly not trying to replace it, but instead provide an alternative for developers to get started with RN. Something that is a little more visual than a CLI.



> There are often breaking changes in RN/RNW across (minor) releases. The project templates and build infrastructure changes from version to version. We expect most people will be using a project that was generated with our CLI, so I'd be concerned about there being "yet another way to create a RNW app", and what the compatibility and migration story would be

Thank you for pointing this out. Since we would depend on the CLI for initial template creation we would look at updating our templates based on CLI changes for our releases. We are still defining this story and the feedback really helps thanks again!

**Comment by sibille** [comment]
Verified in nightly version: 
Templates version: 0.3.21131.1
Wizard version: 0.3.2113101
