### ISSUE TITLE
React Native: Add project type page

### ISSUE THREAD

**Issue by prupipho** [Microsoft/WebTemplateStudio#1664]
Related to #1662  

In order to support the addition of creating React Native applications on Web Template Studio we need a new page to choose the type of project we want to generate (Currently thinking on: Tab or Drawer).

Just to get a feeling of how the Wizard (WTS) will look once we add the Drawer navigation type of app we add here some screenshots of it.

Notice the steps change slightly from the Web Application creation, no Frameworks and Services steps but we have a new Step `Project Type`

![image](https://user-images.githubusercontent.com/1333036/102334589-247d5980-3f8f-11eb-8ebc-974b24874210.png)

**Comment by prupipho** [comment]
Make sure that we don´t display in the right-side bar when not necessary.

Web              -> Project type (fullStack)
React Native  -> Frontend (React Native)

**Comment by dgomezc** [comment]
Checked on nightly version:

Templates version: 0.3.21047.1
Wizard version: 0.3.2104701
