### ISSUE TITLE
React Native: Add entry point for React Native 

### ISSUE THREAD

**Issue by prupipho** [Microsoft/WebTemplateStudio#1666]
Related to #1662

In order to start creating a React Native app using Web Template Studio we need a new command to start the new version of the wizard with the configuration for it.

## Screenshots

![image](https://user-images.githubusercontent.com/1333036/114862500-e6822c00-9dee-11eb-982c-16e36e37a8ec.png)
![image](https://user-images.githubusercontent.com/1333036/114862505-e7b35900-9dee-11eb-85eb-fb37615d9f41.png)

**Comment by dgomezc** [comment]
When the PR is merged, we have to make the following changes to the build:

- Modify "Update Extension Name and version" task arguments:

`-extensionPath "$(Build.SourcesDirectory)/src/extension" -vsixName "$(EXTENSIONNAME)" -vsixDisplayName "$(DISPLAYNAME)" -versionNumber "$(Build.BuildNumber)"  -aiKey "$(AIKEY)" -commandCategory "$(COMMANDCATEGORY)" -createWebAppCommand "$(CREATEWEBAPPCOMMAND)" -deployWebAppCommand "$(DEPLOYWEBAPPCOMMAND)" -createReactNativeAppCommand "$(CREATEREACTNATIVEAPPCOMMAND)"`

- remove variables:
  - WIZARDLAUNCHCOMMAND
  - DEPLOYAPPCOMMAND

- add variables:
  - CREATEWEBAPPCOMMAND = webTemplateStudioExtension.web.createApp.nightly
  - DEPLOYWEBAPPCOMMAND = webTemplateStudioExtension.web.deployApp.nightly
  - CREATEREACTNATIVEAPPCOMMAND = webTemplateStudioExtension.reactNative.createApp.nightly

- Add packaging step for RN templates
- Add replacement for RN package hash

**Comment by prupipho** [comment]
_**Depending on the status of the functionality by the time of the release, we should probably consider to change the name of the command.**_

In order to support the creation with the WTS of react native apps, you will find the following options to Launch `Web Template Studio` depending on the type of Application that you want to create.
```
Web Template Studio {environment}: Create Web App
Web Template Studio {environment}: Create React Native App
Web Template Studio {environment}: Deploy App
```

![image](https://user-images.githubusercontent.com/1333036/102209226-c25e1f00-3ed0-11eb-98dd-e00322b6fa44.png)

_Note:_ Currently we are not planning on Deploy the React Native app using the Command Palette as it needs further investigation and it won´t probably be possible to upload like this to the different marketplaces.

**Comment by prupipho** [comment]
Tested on nightly version:

```
Templates version: 0.3.21015.1
Wizard version: 0.3.2101501
```

**Note:** At the time of the Release we may want to add a (WIP) to the Create React Native command to make it clear that it´s still not fully functional

**Comment by prupipho** [comment]
Add Preview flag. With (Preview) and info icon.

**Comment by prupipho** [comment]
Tested on nightly build:

Templates version: 0.3.21113.4
Wizard version: 0.3.2111304
