### ISSUE TITLE
React Native: Add React Native documentation

### ISSUE THREAD

**Issue by prupipho** [Microsoft/WebTemplateStudio#1671]
Related to #1662

Do not forget .md such as https://github.com/microsoft/WebTemplateStudio/blob/dev/docs/contributing/templates.md

- [x] Generated apps readme should be updated properly.
- [x] Known issues for outstanding work or bugs
- [x] New Pages: Settings
- [x] Theming information
- [x] Master Detail Page (700 width)
- [x] Project Type
- [x] Telemetry (doesn´t need that needs changing)
- [x] New entry point
- [x] Documentation and links
- [ ] Screenshots
     - [x] Android
     - [x] Windows 
     - [ ] iOS

**Comment by sibille** [comment]
Verified in dev
