### ISSUE TITLE
React Native: Update texts on Step 1: New Project Page 

### ISSUE THREAD

**Issue by prupipho** [Microsoft/WebTemplateStudio#1672]
In order to support creation of React Native apps we should make the texts on the main page dynamic depending on the type of platform we are choosing.

Add some text to make it clear that it is still Work in Progress and ask for feedback. We can do the same to the generated readme.

_Create React Native App_ vs _Create Your Web App_

![image](https://user-images.githubusercontent.com/1333036/98940862-f0c09700-24eb-11eb-920e-04f4626a74ce.png)

**Comment by dgomezc** [comment]
Checked on nightly version:

Templates version: 0.3.21047.1
Wizard version: 0.3.2104701
