### ISSUE TITLE
Web Template Studio: Deploy App stopped working after update to VS Code 1.52

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1696]
**Describe the bug**
`Web Template Studio: Deploy App` command stopped working after update to VS Code 1.52. 
Underlying issue is that this command internally calls the task "Install dependencies" which returns the error  "_Tasks to execute must include an execution_". This task is a compound task, that does not have an execution context itself. 
 

**To Reproduce**
1. Open Web Template Studio using the command `Web Template Studio: Launch`.
2. Create a new web application including an Azure App Service.
3. Open the created app.
4. Use command `Web Template Studio: Deploy App` to deploy the App to Azure App Service.

**Expected behavior**
This command should deploy the app.

**Workaround**
You can deploy the app executing the following steps:  
1. Use the VS Code Command `Task: Run Task` to execute the following commands:
    1. Install dependencies
    2. Publish 

 2.  Use the VS Code Command `Azure App Service: Deploy to Web App` to deploy the app to Azure.

**System**

- **VS Code Version: 1.52.0** 
- **Templates version: 0.5.20323.1**
- **Wizard version: 0.5.2032301**

**Comment by prupipho** [comment]
Tested on Dev version and Deploy is back to action!

**Comment by sibille** [comment]
Verified on nightly build: 
Templates version: 0.3.21078.1
Wizard version: 0.3.2107801
