### ISSUE TITLE
Fix warnings in client 

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1706]
After updating to react-scripts 4,0.1 in  https://github.com/microsoft/WebTemplateStudio/pull/1702 the following warning appeared.

```
Type: warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types

✖ 176 problems (0 errors, 176 warnings)
```

We should fix this by adding the return type to exported functions.

**Comment by dgomezc** [comment]
Verified on nightly build:
Templates version: 0.3.21084.1
Wizard version: 0.3.2108401
