### ISSUE TITLE
Clean up handling for the extension to the API

### ISSUE THREAD

**Issue by SahilTara** [microsoft/WebTemplateStudio#172]
- [x] Change createSignalR.. method to establishSignalR..
- [x] Call postConnectionHandler in the establishSignalR... method rather than the current method
- [x] Clean up sync api.
- [ ] Figure out a better way to do retries or consider sending a message to the extension to initiate connection.
~Use https~ No longer being considered since always local host and would create bad UX since the user would have to trust the cert manually.

**Comment by Tanya0609** [comment]
Since the extension to API has been refactored by Juan and we are moving from extension to API to extension to CLI, thus this issue will no longer apply. Closing this issue
