### ISSUE TITLE
Control in client "wts.multipleInstance" flag: only one Settings Page per application

### ISSUE THREAD

**Issue by prupipho** [Microsoft/WebTemplateStudio#1729]
We need to control the flag **"wts.multipleInstance"** so we can control in the client when there´s an scenario like the Settings Page:
- only one Settings Page per application.

Currently if we add that flag:
- it doesn´t allow editing the name.
- it allows you to create multiple pages.

What we expect:
- it should only allow to add one Setting Page per application.

![image](https://user-images.githubusercontent.com/1333036/108822944-14ea4480-75c0-11eb-8db7-5a52a21f1c81.png)

**Comment by dgomezc** [comment]
Verified on nightly build:
Templates version: 0.3.21084.1
Wizard version: 0.3.2108401
