### ISSUE TITLE
Wizard: Add more description texts

### ISSUE THREAD

**Issue by prupipho** [Microsoft/WebTemplateStudio#1738]
After applying changes to the wizard we should add more description texts on the templates so we provide more info during the Wizard experience on the **Add Framework** and **Add Pages** Steps.

Change the short description to be longer so the cards are not that empty now that we won room with smaller font-sizes.

### Screenshots with changes

![image](https://user-images.githubusercontent.com/1333036/115233658-7b02cc00-a118-11eb-987f-e08fda530981.png)

Just for reference see images below:

![image](https://user-images.githubusercontent.com/1333036/109962028-018b5780-7ceb-11eb-9e63-289cb2107ce1.png)

![image](https://user-images.githubusercontent.com/1333036/109962077-10720a00-7ceb-11eb-8923-ed3969f5699b.png)

**Comment by sibille** [comment]
Verified in nightly version:
Templates version: 0.3.21127.1
Wizard version: 0.3.2112701

**Comment by prupipho** [comment]
Reviewed again in nightly build:

Templates version: 0.3.21131.1
Wizard version: 0.3.2113101
