### ISSUE TITLE
Wizard React Native App: should sync project Name value correctly

### ISSUE THREAD

**Issue by prupipho** [Microsoft/WebTemplateStudio#1742]
**Describe the bug**
When updating the wizard to allow creating React Native Apps we accidentally broke the project Name syncronisation in the Project Name page and the rightside bar.

**To Reproduce**
1. Open Web Templates Studio with option "Create React Native App"
2. Write a name for your project
3. Notice that it doesn´t update correctly on the Rightside bar

**Expected behavior**
Project Name input should update at the same time when editing it, no matter where.

**Screenshots**
![image](https://user-images.githubusercontent.com/1333036/110012391-c572e980-7d20-11eb-8046-aa597fa6d3c6.png)

**Comment by dgomezc** [comment]
Verified on nightly build:
Templates version: 0.3.21084.1
Wizard version: 0.3.2108401
