### ISSUE TITLE
Update npm/nuget packages to latest version in generated app

### ISSUE THREAD

**Issue by prupipho** [Microsoft/WebTemplateStudio#1775]
Update packages for Web dependencies generated apps. According to CLI.

## Frontend Framework
- [x] React
- [x] Angular
- [x] Vue 

## Backend Framework
- [x] Node 
- [x] Asp.net 
- [x] Flask 
- [x] Moleculer

**Comment by sibille** [comment]
Verified on nightly version:
Templates version: 0.3.21131.1
Wizard version: 0.3.2113101
