### ISSUE TITLE
Use destructured variables where possible.

### ISSUE THREAD

**Issue by SahilTara** [microsoft/WebTemplateStudio#190]
We need to use destructured variables where possible so that our code is cleaner.

**Comment by xtinah-w** [comment]
@SahilTara Can you give an example or more explanation on this please?

**Comment by SahilTara** [comment]
Oh haha maybe this is fixed but @xtinah-w I essentially meant to destructure the variables whenever possible. For example imagine you have an object props, with the following attributes: foo, bar.

Instead of doing `props.foo` and `props.bar` you would do `const {foo, bar} = props` and then call `foo` and `bar` respectively in the code instead. Removes the extra "props.". This issue can probably be closed now.
