### ISSUE TITLE
Add in Angular support

### ISSUE THREAD

**Issue by crutkas** [microsoft/WebTemplateStudio#198]

**Comment by crutkas** [comment]
this isn't done.  it is still behind a settings flag

**Comment by SahilTara** [comment]
Hey Clint, Angular has full feature parity with react, opening this issue again doesn't seem necessary. If you think angular shouldn't have the preview flag it should be a seperate issue. I would add the good first issue tag to it as well since its a 1 line change.

**Comment by crutkas** [comment]
eh ... i disagree but will create a new issue and link
