### ISSUE TITLE
Add in ASP.NET Core support

### ISSUE THREAD

**Issue by crutkas** [microsoft/WebTemplateStudio#200]
Add ASP.NET Core 3.1 Web API as a backend framework option.

Action Plan: 

- [x] Create Mockup project
- [ ] Validate Mockups
- [x] Create templates
- [x] Adapt dependency checker to include .NET Core dependencies
- [x] Adapt extension to update appsettings.json with connection string
- [x] Update docs

**Comment by hansmbakker** [comment]
@xtinah-w can you give a rationale why you added the wontfix label? I think Asp.Net Core really would be a useful addition to Web Template Studio.

**Comment by Tanya0609** [comment]
Hi @hansmbakker, I think @xtinah-w mean wont be able to do it within the Aug 2019 deadline. We created and changed to oos label, this is more accurate label.

Add support for .NET is something we would love to do, and we have reached out to the team that is developing .NET projects. They would like to support us once we start this feature. Hope this will be dev hours on this feature in the very soon future!

**Comment by hansmbakker** [comment]
Great to hear!

**Comment by NLI-KelbyHunt** [comment]
Hoping for a couple of templates out of this;

- ASP Core MVC Razor
- ASP Core Razor Component
- ASP Core Worker Service

Probably more.

**Comment by smadgerano** [comment]
Just wanted to add my voice to this, as well as the suggestions by @NLI-KelbyHunt I would also add in ASP Core Razor Pages as a good first stage, with Blazor afterwards - this would make scaffoilding a new project sooooooo much easier and I would love you forever MS, promise, pinky promise :)

**Comment by IvanJosipovic** [comment]
ASP.Net Core and Blazor are a must!

**Comment by sibille** [comment]
We're looking into adding a ASP.NET Core WebAPI backend, I've updated the Action Plan for this issue.

This also need's issue #1469 to parse data in ASP.NET and to share the same model among all Front and Backends.

**Comment by sibille** [comment]
We'll put this into preview for now as we are still waiting for the mockup validation

**Comment by sibille** [comment]
Opened issue https://github.com/microsoft/WebTemplateStudio/issues/1543 to move ASP.NET out of preview in version 0.5

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.3.20197.2
Wizard version: 0.3.2019702
