### ISSUE TITLE
Tell user when dependency is required/nice to have

### ISSUE THREAD

**Issue by crutkas** [microsoft/WebTemplateStudio#302]
currently the extension has requirements for end user to have items like Yarn or Node preinstalled.  The ext should detect that a requirement is not there and tell the user.

Yarn, CosmosDB ext, ... are great examples of "better together" examples.
Node.js is a must have requirement.

This is two parts
- [ ] Required item
- [ ] Better together items

Suggested json adjustments
- [ ] name
- [ ] Install URI
- [ ] About URI

Where it would display
- Summary screen with warning / informational 
- Readme we generate

**Comment by Tanya0609** [comment]
We introduced dependency checker recently, this fulfills this issue, thus close this issue
