### ISSUE TITLE
Adding and removing pages does not reset the page name counter.

### ISSUE THREAD

**Issue by JimmyH936** [microsoft/WebTemplateStudio#359]
This is the case for all pages.

Steps to reproduce:

1. Launch Wizard
2. Go to pages
3. Delete the default added Blank Page.
4. re-add the blank page

Under project details, it will appear as (Blank2) instead of just (Blank).

**Comment by Tanya0609** [comment]
This is related to re-design the paging name logic.

**Comment by sibille** [comment]
Fixed as part of https://github.com/microsoft/WebTemplateStudio/pull/1309

Verified in dev-nightly:
Templates version: 0.1.20028.1
Wizard version: 0.1.2002801
