### ISSUE TITLE
Azure Sign in does not display anything if user tries to sign in and there is no internet connection.

### ISSUE THREAD

**Issue by amrrsharaff** [microsoft/WebTemplateStudio#361]
Repro steps:
1- Launch the wizard and turn off the wifi (internet needs to be disconnected)
2- Proceed to Azure Sign in Page 
3- Click on sign in a few times
4- You will find that nothing happens
5- Turn on the wifi
6- Multiple tabs will open for sign in.

There needs to be internet connection validation before we execute the login command.

**Comment by jcoc611-microsoft** [comment]
This is an upstream issue from `azure-account`, see the bug [here](https://github.com/microsoft/vscode-azure-account/issues/141)

**Comment by prupipho** [comment]
This seems to be solved now. Doesn´t show the same message when logging out but doesn´t seem to be a problem on that scenario.

![image](https://user-images.githubusercontent.com/1333036/96577886-a07f5c00-12d4-11eb-9cab-0e495d466f63.png)
