### ISSUE TITLE
Running the sign out command in vscode does not update the status in the wizard.

### ISSUE THREAD

**Issue by JimmyH936** [microsoft/WebTemplateStudio#393]
![Bug 6](https://user-images.githubusercontent.com/46546396/55839193-daff1a80-5adb-11e9-8ee6-afd6a6719627.PNG)

If I am already signed into Azure before launching the wizard and I sign out using the command line, the wizard still shows that I am signed in although I am signed out in VS Code

**Comment by sibille** [comment]
Verified in version: 
Templates version: 0.0.19298.1
Wizard version: 0.0.1929801
