### ISSUE TITLE
Add a .VSCode to generated code

### ISSUE THREAD

**Issue by dandua98** [microsoft/WebTemplateStudio#412]
We need to add a .VSCode to be generated for the user to be able to run the frontend and backend at once through VSCode

**Comment by SahilTara** [comment]
@xtinah-w Why the wont fix here?

**Comment by Tanya0609** [comment]
Hi, I think wont fix mean wont fix within the scope to end of August. Using oos will be more accurate in this case.

**Comment by prupipho** [comment]
Generated apps already contain this folder.

![image](https://user-images.githubusercontent.com/1333036/96578517-9e69cd00-12d5-11eb-84b8-afcb1529b8d6.png)
