### ISSUE TITLE
Create a key shortcut to run the extension

### ISSUE THREAD

**Issue by traore-i** [microsoft/WebTemplateStudio#472]
Create a shortcut, example: `Ctrl+Shift+A` mapped to `Web Template Studio : Launch`

**Comment by SahilTara** [comment]
Shouldn't be too bad just add the following to contributes in the extension [package.json](https://github.com/microsoft/WebTemplateStudio/blob/dev/src/extension/package.json)
```json
    "keybindings": [
        {
            "command": "webTemplateStudioExtension.wizardLaunch",
            "key": "ctrl+shift+a",
            "mac": "shift+cmd+a"
        },
    ]
```

**Comment by SahilTara** [comment]
Closing and tagged since we don't want to pollute the user's key bindings.
