### ISSUE TITLE
First launch takes very long

### ISSUE THREAD

**Issue by traore-i** [microsoft/WebTemplateStudio#474]

**Comment by crutkas** [comment]
This is still an issue we need to resolve

**Comment by SahilTara** [comment]
Most of the launch time has to do with launching of the local API. If you can figure out a way to reduce the boot time you'll reduce time by a lot! If you somehow find out how to extract the file faster that would also help, but I cannot see how you would go about that at the moment, if at all possible.

Things that cannot be controlled:
- How fast the extension initializes (this refers to the time between hitting ctrl-shift-p then launching webts and the pop up showing up in the bottom right).

**Comment by crutkas** [comment]
@SahilTara there are lots of ways to hide load and give instance response.

**Comment by jcoc611-microsoft** [comment]
Sped up with CLI work replacing API
