### ISSUE TITLE
We need to templatize Azure Functions arm templates, into engine templates.

### ISSUE THREAD

**Issue by SahilTara** [microsoft/WebTemplateStudio#479]
Currently we use the extension to generate an arm-template folder and it does the bulk of the stuff regarding azure functions. We need to abstract the replacement process out into templates usable by corets.

The following changes will need to be made to support this:
1) Pass the function app name to the engine via gen payload
2) Create capability for Param_FunctionAppName or something of the sort within the engine. To allow for the following folder structure:
```
├── Param_FunctionAppName
│ ├── Name of Function 0
│ ├── Name of Function 1
.
.
.

```

We will then need to do the appropriate merging of the .vscode to be able to give a f5 experience specific for functions.

**Comment by sibille** [comment]
We're not generating Azure Functions anymore.
