### ISSUE TITLE
About widget should be bottom aligned

### ISSUE THREAD

**Issue by crutkas** [microsoft/WebTemplateStudio#483]
![image](https://user-images.githubusercontent.com/1462282/56322305-897b0f00-611d-11e9-922b-f53a7bd41401.png)

![image](https://user-images.githubusercontent.com/1462282/56322345-ac0d2800-611d-11e9-921d-5718a15a4153.png)

**Comment by Tanya0609** [comment]
This enhancement is already in the Wizard, thus closing this issue
