### ISSUE TITLE
When spinner is rotating, rendering becomes blurry on lo-res displays (Mac OSX)

### ISSUE THREAD

**Issue by ngkelly3** [microsoft/WebTemplateStudio#491]
Repro steps:
- Open WTS
- Select React
- Select Node
- Select pages
- Do not select Azure Services (click next)
- Click "Generate"

Expected Behaviour:
- Post gen modal opens and spinner runs indicating "working"
- No change in rendering other than spinner spinning

Actual Behaviour:
- Same behaviour as above except entire screen becomes slightly blurry

**Comment by prupipho** [comment]
Seems that it is ok now. Tested on a laptop with 1024x768 and seems to display correctly
