### ISSUE TITLE
Location dropdown(up) in Azure Functions is being cutoff (still functional)

### ISSUE THREAD

**Issue by markAtMicrosoft** [microsoft/WebTemplateStudio#505]
Repro steps:

1. Open WebTS
2. Select ReactJS
3. Select NodeJS
4. Sign into Azure
5. Add Azure Functions
6. Open Locations Dropdown

Expected Behaviour:
Dropdown is fully visible in window.
Actual Behaviour:
Frame of dropdown/up is being cut off. (see attached image).  All items in dropdown are displaying properly.  Just the frame is truncated.
![image](https://user-images.githubusercontent.com/34253371/56380021-e7633180-61c5-11e9-8e21-6186cc1faf61.png)

**Comment by streetcoder123** [comment]
@jsondoo Can you reproduce this?

**Comment by streetcoder123** [comment]
This issue has been fixed.
