### ISSUE TITLE
Summary Page Hover Title on Icon

### ISSUE THREAD

**Issue by trevorNgo** [microsoft/WebTemplateStudio#507]
![image](https://user-images.githubusercontent.com/23327878/56381189-00211680-61c9-11e9-8705-d448c91aa12e.png)
Should be changed to "Edit Individual Function Name"...

**Comment by crutkas** [comment]
This could be an issue across all Alt text (which is a must for accessibility

**Comment by Hardik500** [comment]
This issue has already been fixed. So why not close it down.
