### ISSUE TITLE
Deleting all of Azure individual Functions should remove from Cart

### ISSUE THREAD

**Issue by trevorNgo** [microsoft/WebTemplateStudio#536]
![image](https://user-images.githubusercontent.com/23327878/56597392-3682db00-65a7-11e9-9c40-9a00ed7955e0.png)

In summary page, delete all azure functions

**Comment by streetcoder123** [comment]
This is fixed. Now, if only 1 azure function is left, you can only delete the azure functions group and not the individual azure function.
