### ISSUE TITLE
Wizard UX lacks any mouse hover feedback - 0.0.19112-4

### ISSUE THREAD

**Issue by crutkas** [microsoft/WebTemplateStudio#550]
hovering over anything, you don't get any visual feedback.  Left nav, bottom "back"/"next" buttons, ....  Subtle detail but very helpful wayfinding for where you are in a UX

**Comment by prupipho** [comment]
@sibille I think this could be not to hard to do, and I also feel the same way about no hover feedback.

**Comment by sibille** [comment]
Agree, think this is a good candidate for milestone 0.6

**Comment by dgomezc** [comment]
When back or next button are disabled, no feedback should be provided.

**Comment by prupipho** [comment]
Checked on:
Templates version: 0.3.21068.1
Wizard version: 0.3.2106801
