### ISSUE TITLE
Bootstrap list template should add an item on Enter Key press

### ISSUE THREAD

**Issue by dandua98** [microsoft/WebTemplateStudio#570]
![image](https://user-images.githubusercontent.com/24802378/56774713-c035d280-6778-11e9-88e1-c534663dcd77.png)

Pressing enter on a list item should add the item to list, this would be more intuitive.

**Comment by crutkas** [comment]
angular should be updated as well as react

**Comment by crutkas** [comment]
i think we also need to have maybe documented page behaviors so when new frameworks come online / something is adjusted, it is documented it should act the same across the board.

**Comment by crutkas** [comment]
This is another great chance to maybe add in a web ui test :)

**Comment by streetcoder123** [comment]
This issue has been fixed
