### ISSUE TITLE
Pages should revalidate for duplicate names on adding a new page

### ISSUE THREAD

**Issue by dandua98** [microsoft/WebTemplateStudio#572]
![image](https://user-images.githubusercontent.com/24802378/56775212-f2e0ca80-677a-11e9-9ce6-ea23fdabff7d.png)

_**Repro steps:**_

- Launch the extension and navigate to the pages screen
- Add a page of any type (let's say *grid*)
- Rename the added *grid* page from *Grid* to *Grid2*
- Add another grid page
- At this point you have 2 grid pages with name *Grid2* but no error to inform you about this. The generate button is disable on summary page but there are no validation helpers guiding you.

You can also replicate this bug by renaming any page to a name that will be generated when you add a new page. (For ex: renaming a page to *Grid6* when you're about to add a 6th grid page)

**Comment by sibille** [comment]
Fixed as part of https://github.com/microsoft/WebTemplateStudio/pull/1309

Verified in dev-nightly:
Templates version: 0.1.20028.1
Wizard version: 0.1.2002801
