### ISSUE TITLE
It is odd for the page number to increment even after deleting all pages.

### ISSUE THREAD

**Issue by SahilTara** [Microsoft/WebTemplateStudio#583]
Hey,
I've been doing some user testing and found that people don't like us having to increment the pages even after all other pages have been deleted.

To have a better sense of what I mean do the following:
1) Add three blank pages, you should now have Blank page, Blank page1, Blank page2
2) Remove all blank pages, you should now have 0 pages selected.
3) Add another blank page, you should now have Blank page3 selected.

It is odd to have Blank page3 when there's no other blank pages.

Make sure this is done in a way that it doesn't introduce any new bugs though! Since this was originally done to prevent some other bugs. 

#246 This essentially had to do with the counter resetting and allowing the user to have 2 pages  as "Blank Page3" which didn't get validated.

My suggestion would be to do a check of some kind by adding items to a set or something and ensuring the newly generated name does not exist in this set. If the name does exist in the set we increment our number, otherwise we don't.

However, if you can come up with a better solution then that would be great!

**Comment by JimmyH936** [comment]
I also agree with this issue from a UX perspective. I think this is something we spotted earlier but decided to prioritize other issues instead.

**Comment by sibille** [comment]
Dup of https://github.com/microsoft/WebTemplateStudio/issues/359
