### ISSUE TITLE
WebTemplateStudio + PWA + Blazor

### ISSUE THREAD

**Issue by ViViVerse** [Microsoft/WebTemplateStudio#586]
I am a beginner with this. Could somebody please explain me whether it should be possible to combine the three 'techniques' mentioned in the title?

**Comment by crutkas** [comment]
Pwa is one item we are looking at but currently we do not support blazor for generation. Great idea. 

Let’s close this issue out and each pwa and blazor independently

**Comment by crutkas** [comment]
Created two more targetted issues @ViViVerse :)

**Comment by ViViVerse** [comment]
Great, looking forward to see it!
