### ISSUE TITLE
Always allow to generate

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#588]
The generate button should be enabled, once you chose project name and path. First project type and frameworks should be selected to generate with default configuration. 

Also, the buttons label "Generate templates" is confusing, I think we should use "Create" as in WinTS.

**Comment by xtinah-w** [comment]
We have addressed this in the current flow and have activated Generate Template once a user reaches the Summary page (since every decision is dependent on previous decisions made). Closing this issue.
