### ISSUE TITLE
AngularJS should rename to just Angular

### ISSUE THREAD

**Issue by doggy8088** [Microsoft/WebTemplateStudio#599]
I've just seen "**AngularJS**" in the WTS preview mode. The name **AngularJS** should correct to **Angular** for better understanding.

**Comment by crutkas** [comment]
Agreed. Their docs reference angular. https://github.com/angular/angular

**Comment by sibille** [comment]
@jsondoo, can we change the internal name to Angular for consistensy too? You'll have to change it on the fronendframework.json, and also on the projects and page templates + compositions too

**Comment by jsondoo** [comment]
@sibille yes I will look into it
