### ISSUE TITLE
Could not sync to template repository

### ISSUE THREAD

**Issue by elisco-latour** [Microsoft/WebTemplateStudio#601]
Repro steps:

1.
2.

Action: Sync-Engine
Error type: Error
Error Message: Could not sync to template repository

Version: 0.0.1913418
OS: darwin
VS Code Version: 1.34.0

<details>
<summary>Call Stack</summary>

```
LaunchExperience.<anonymous> (/Users/<user>/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.0.1913418/out/launchExperience.js:39:23)
Generator.next (<anonymous>)
fulfilled (/Users/koffielikponblanou/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.0.1913418/out/launchExperience.js:4:58)
```

</details>

**Comment by crutkas** [comment]
my gut says this is #392

**Comment by sibille** [comment]
@elisco-latour, could you update to version 0.0.1914003? This should be fixed now.

**Comment by dzg** [comment]
I'm on 0.0.1914003 and getting same error.

Action: Sync-Engine
Error type: Error
Error Message: Could not sync to template repository

Version: 0.0.1914003
OS: darwin
VS Code Version: 1.34.0

<details>
<summary>Call Stack</summary>

```
LaunchExperience.<anonymous> (/Users/<user>/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.0.1914003/out/launchExperience.js:39:23)
Generator.next (<anonymous>)
fulfilled (/Users/dang/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.0.1914003/out/launchExperience.js:4:58)
```

</details>

**Comment by sibille** [comment]
@dzg, thanks for reporting. 
Some more questions to further diagnose and try to repro: 
- What exact OS version are you using? 
- Do you see any logs in the folder "/Users/[username]/.local/share/WebTS/Logs"? Could you share them?

**Comment by dzg** [comment]
> @dzg, thanks for reporting.
> Some more questions to further diagnose and try to repro:
> 
> * What exact OS version are you using?

OSX v 10.11.6 (15G1421)

> * Do you see any logs in the folder "/Users/[username]/.local/share/WebTS/Logs"? Could you share them?

Sorry, there is no `WebTS` folder in `~/.local/share`

**Comment by sibille** [comment]
Thanks @dgz! 
/Users/[username]/.local/share/WebTS/ is the folder where templates are synchronized, does your user have write permissions on /Users/[username]/.local/share?

**Comment by dzg** [comment]
Hi @sibille, 
> /Users/[username]/.local/share/WebTS/ is the folder where templates are synchronized, does your user have write permissions on /Users/[username]/.local/share?

I was able to `mkdir ~/.local/share/WebTS` and `touch ~/.local/share/WebTS/123` from same user running VS Code.

But I still get `Could not sync to template repository `

Can I change that to some other path?

**Comment by sibille** [comment]
Sorry @dzg, we're using the LocalApplicationData folder to sync templates, this cannot be changed. 
If you have write access to this directory, permissions do not seem to be the problem. 
We'll try to get a repo with the same OS version. 
Also think we should add more info about the underlying error on the output.

**Comment by adamelliotfields** [comment]
Just ran into this myself. Mojave 10.14.5. Code 1.34.0. Node 10.15.3 (Dubnium LTS). Yarn 1.16.0.

`mkdir -p ~/.local/share/WebTS` worked after I manually restarted VS Code.

I was already logged into Azure, if that helps too!

**Comment by sibille** [comment]
@adamelliotfields so, once you created the directory manually sync worked?

**Comment by adamelliotfields** [comment]
Yup! From there I was able to create a project using the React/Express template.

cc: @sibille

**Comment by xtinah-w** [comment]
Solved, closing this issue.
