### ISSUE TITLE
Installation progress

### ISSUE THREAD

**Issue by FDiskas** [Microsoft/WebTemplateStudio#603]
Add progress or status of current installation. Current extension takes long time to install

**Comment by crutkas** [comment]
Can you share the specs of your machine?  Install is done by vs market place and vs code so we can’t really do much about it. One issue could be size of plugin and that is due to us supporting Linux, Mac and Windows.

**Comment by FDiskas** [comment]
```
Version: 1.34.0
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:55:35.507Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-30deepin-generic
```

**Comment by crutkas** [comment]
More like processor and type of HD and internet speed.

**Comment by dandua98** [comment]
I had first install taking forever on a `MacBook Pro 2015` with `16GB of RAM` too. More like it installed and just got stuck. On quitting and restarting VSCode, the extension was already installed even though the installation process took forever and didn't give any notifications about completion

**Comment by crutkas** [comment]
Ok. Will see if I can’t grab a MBP and test to see if it is an easy repro

**Comment by ngkelly3** [comment]
@FDiskas was there activity on the progress bar on the extension menu? this is currently how vscode shows extension installation progress.

**Comment by sibille** [comment]
There is an issue on VSCode repo code repo for this https://github.com/microsoft/vscode/issues/56023
