### ISSUE TITLE
Make Angular support out of preview

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WebTemplateStudio#605]
From issue #198 , @SahilTara believes this is at parity with the React framework.  The task that is needed is to flip the template out of preview.

Work that is needed

- [ ] Verify 1 to 1 support with React
- [ ] Change template out of preview mode

**Comment by crutkas** [comment]
one this is done, we can close out #198

**Comment by Tanya0609** [comment]
Angular is out of preview mode in June 24, thus close this issue
