### ISSUE TITLE
i cannot see anything on step 2,step 3,step 4

### ISSUE THREAD

**Issue by duanerlong** [Microsoft/WebTemplateStudio#612]
vs code Insiders

**Comment by crutkas** [comment]
Can you provide exact version of wts, vs code and OS you are on

**Comment by ngkelly3** [comment]
@duanerlong please include a screenshot

**Comment by duanerlong** [comment]
@crutkas 
Visual Studio Code - Insiders

Version: 1.35.0-insider (user setup)
Commit: 94f7de61ece171f4390ece488a220d22cbb0fddd
Date: 2019-05-23T05:19:33.101Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601


remote pc

Linux v4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by duanerlong** [comment]
@ngkelly3 
![step2](https://user-images.githubusercontent.com/7604240/58301922-6aaa1f80-7e23-11e9-9e23-d2fac1fb45bf.png)
![step3](https://user-images.githubusercontent.com/7604240/58301923-6b42b600-7e23-11e9-934d-7c85f804b784.png)
![step4](https://user-images.githubusercontent.com/7604240/58301925-6b42b600-7e23-11e9-9db0-a91e35073043.png)

**Comment by trevorNgo** [comment]
> @ngkelly3 @SahilTara  looks like template sync issue with linux + insiders?...

**Comment by SahilTara** [comment]
@trevorNgo Odd since if templates can't sync it shouldn't even launch the wizard. Notice that there is no wizard version either. The wizard version isn't provided through the core its provided through the extension itself. I'll look at it later in the day to see if I can repro it. I have a feeling its something to do with the wizard + ssh. Could be linux + insiders as you said though.

**Comment by crutkas** [comment]
Could be a remoting scenario we never thought of.

**Comment by duanerlong** [comment]
Maybe the extension's backend is not running properly in remote mode.
I am running Web Template Studio in both normal mode and remote mode. In this case, the remote mode Web Template Studio can also be used.

**Comment by Tanya0609** [comment]
Hi @duanerlong, the solution to this issue has been merged into our code base, and will be released next Monday. Please download the new release extension from marketplace or update your current extension, and the issue should be fixed for you. Thus, will close this issue for now.

If the issue still exists, please let us know! Thank you so much for your feedback!
