### ISSUE TITLE
Move the side nav bar to a top nav

### ISSUE THREAD

**Issue by xtinah-w** [Microsoft/WebTemplateStudio#619]
We need to open up the space currently occupied by the side nav in order to provide more space for more pertinent information to the user. This will also be less distracting as we read from right to left (you read what you need faster with less noise).

**Comment by mrlacey** [comment]
Which navigation bar?

**Comment by xtinah-w** [comment]
![navBar](https://user-images.githubusercontent.com/24245311/58435261-86f0cb00-8074-11e9-8200-3ed0f046419b.png)

Moving this side nav bar to the top bar to free up more screen real estate which allows people to read from left to right without the distraction of the subsection titles. 

It also allows us to put in previews of pages on the "Pages" section without feeling restricted by the amount of space we have to work with (reduces the need to click to view the template).

Still working on this user flow though!

**Comment by mrlacey** [comment]
If you put the step titles across the top, doesn't this force them all to be read "from left to right"? Even though they don't all need to be read initially?

How would you handle the lack of space to fully display all steps across the available space?

What's the goal here?
What options are available?

You've started by stating a design change of "move the nav bar" and then tried to justify it.  If you're "working on this user flow", don't create issues to make specific changes before the full requirements are understood.

Have people complained about  subsection titles being distracting? What do you mean by "subsection titles"?

Has there been feedback from actual people using the tool that having to click the 'details' text to see what is actually included in a page is a problem? Is this only something people want to do the first time they use the wizard? Or do people using the wizard repeatedly still want the extra information?

How will putting previews of pages in line in the list affect navigating and browsing the list as the number of pages grows?

Will including a large page preview mean doing away with the need to have a details page?

The "Services" step already has larger item containers. How will making the page items larger necessitate needing to change the location of the navigation controls?

**Comment by xtinah-w** [comment]
All very valid questions - thank you for bringing them up!

Right now, our team is currently in the middle of conducting our initial round of user testing, after fleshing out our assumptions from the previous sprint. This was an heuristic evaluation we conducted to see where the opportunity areas are. We will be conducting A/B testing to see what the insights are since the consensus on the look/feel is that it feels "clunky/heavy for the amount of steps that are involved with the wizard". This will also include a survey to gather more insights.

Your questions have also given a lot of insight into how we will be approaching our user testing.

Once we finish our initial round of testing, I will be happy to share these insights with you to further address your questions and concerns. Would this be easier to do in a Teams call? If so, please let me know so we can set it up. We will be using them to inform our design. This is also based on some of the leftover user research remaining from the previous team (i.e. Master Details page = many people have no idea what that looks like/means - only until they see what it looks like do they understand). Let me know if this is of interest to you. Thank you, Matt.

**Comment by Tanya0609** [comment]
The feature is in WebTS, thus close this issue
