### ISSUE TITLE
Reword "Enter a project name and output path, then click next to get started" on Home

### ISSUE THREAD

**Issue by xtinah-w** [Microsoft/WebTemplateStudio#620]
Improve match between system and real world speak.

"Create your project name and choose where to save your project, then click "Next" to get started."

Something to that effect

**Comment by mrlacey** [comment]
How about:
"Give your project a name, specify where to create it, then click 'Next' to get started."

**Comment by xtinah-w** [comment]
I think that sounds a lot better - thank you so much for the suggestion!

**Comment by streetcoder123** [comment]
@xtinah-w Should we close this issue now as fixed?
