### ISSUE TITLE
Disable "Add Resource" button if not signed into Azure Services

### ISSUE THREAD

**Issue by xtinah-w** [Microsoft/WebTemplateStudio#623]
Clicking on "Add Resource" crashes the wizard - needs to be disabled until the dev is logged in.

**Comment by crutkas** [comment]
How did the wizard get into this state?  There should be a sign in button

**Comment by crutkas** [comment]
Also what unit tests were added to catch this scenario

**Comment by SahilTara** [comment]
This was an issue for a while it was a low pri item when we did it though. Probs some selenium tests would be one way.
