### ISSUE TITLE
Error message should be more helpful and relieve stress/frustration if template doesn't generate properly

### ISSUE THREAD

**Issue by xtinah-w** [Microsoft/WebTemplateStudio#627]
Errors need to be more specific than what's shown below (experienced by Tanya when booting up WTS in week 1). Not a match between system and real world and invokes frustration from the user (an illustration + helpful prompt can help relieve this pain point in the template generation error process).

Utils.js:217

[2019-05-17T17:36:09.089Z] Information: Connection disconnected. 

Utils.js:217

(node:23576) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. 
warning.js:18

[2019-05-17T17:36:37.643Z] Information: WebSocket connected to ws://localhost:9502/corehub?id=1yeapO3r6solGfaFf-X9hA. 

Utils.js:217

Error: An unexpected error occurred invoking 'Generate' on the server.  at HubConnection.invoke._this.callbacks.(anonymous function) (c:\Users\t-yitan\WebTemplateStudio\src\extension\node_modules\@aspnet\signalr\dist\cjs\HubConnection.js:246:36)  at HubConnection.processIncomingData (c:\Users\t-yitan\WebTemplateStudio\src\extension\node_modules\@aspnet\signalr\dist\cjs\HubConnection.js:340:29)  at WebSocketTransport.HubConnection.HubConnection.connection.onreceive (c:\Users\t-yitan\WebTemplateStudio\src\extension\node_modules\@aspnet\signalr\dist\cjs\HubConnection.js:67:68)  at WebSocketTransport.connect.webSocket.onmessage (c:\Users\t-yitan\WebTemplateStudio\src\extension\node_modules\@aspnet\signalr\dist\cjs\WebSocketTransport.js:109:43)  at WebSocket.onMessage (c:\Users\t-yitan\WebTemplateStudio\src\extension\node_modules\ws\lib\event-target.js:120:16)  at WebSocket.emit (events.js:182:13)  at Receiver.receiverOnMessage (c:\Users\t-yitan\WebTemplateStudio\src\extension\node_modules\ws\lib\websocket.js:792:20)  at Receiver.emit (events.js:182:13)  at Receiver.dataMessage (c:\Users\t-yitan\WebTemplateStudio\src\extension\node_modules\ws\lib\receiver.js:422:14)  at Receiver.getData (c:\Users\t-yitan\WebTemplateStudio\src\extension\node_modules\ws\lib\receiver.js:352:17)  at Receiver.startLoop (c:\Users\t-yitan\WebTemplateStudio\src\extension\node_modules\ws\lib\receiver.js:138:22)  at Receiver._write (c:\Users\t-yitan\WebTemplateStudio\src\extension\node_modules\ws\lib\receiver.js:74:10)  at doWrite (_stream_writable.js:410:12)  at writeOrBuffer (_stream_writable.js:394:5)  at Receiver.Writable.write (_stream_writable.js:294:11)  at Socket.socketOnData (c:\Users\t-yitan\WebTemplateStudio\src\extension\node_modules\ws\lib\websocket.js:867:35)  at Socket.emit (events.js:182:13)  at addChunk (_stream_readable.js:279:12)  at readableAddChunk (_stream_readable.js:264:11)  at Socket.Readable.push (_stream_readable.js:219:10)  at TCP.onread (net.js:636:20)```

**Comment by SahilTara** [comment]
Completely agree with this! Will probably have to make the change on corets first using pipeline module. This will be a great first exposure to the corets repo. Looking forward to seeing the design for this.

**Comment by SahilTara** [comment]
Also @Tanya0609 if you manage to reproduce template gen failure please file an issue right away with repro steps.

**Comment by Tanya0609** [comment]
I fixed the template gen failure by re-clone the GitHub repo. Maybe there would be something to do with previous version of code.

**Comment by sibille** [comment]
This was fixed when we migrated the api to cli
