### ISSUE TITLE
We need to change our local development DLLs to debug mode.

### ISSUE THREAD

**Issue by SahilTara** [Microsoft/WebTemplateStudio#632]
Currently developing templates locally is relatively hard. We need to do packaging locally and this takes  time from all people developing. This also makes testing features a bit harder and causes many merge conflicts. 

I suggest we change the DLLs to debug locally. Changing to debug will allow us to use the raw templates folder without having to:
1) Keep track of template versions
2) Spending time packaging
3) Fixing unnecessary and completely avoidable merge conflicts

@crutkas wondering what your opinion on this is. I have a hunch that this will speed up development on templates significantly. This won't affect release status in our VSIX since it rebuilds CORETS in the build pipeline with the release mode flag. Will only affect local development process.

This will also allow people to work on templates from any OS since currently the packaging tool relies on .NET Framework which is windows only, so testing locally becomes unnecessarily tedious for people not using windows. 

## Will need the following changes:
- [x] change macOS dlls to debug
- [ ] change linux dlls to debug
- [x] change windows dlls to debug
- [x] Add an environment check for debug mode or production, and choose the sync path accordingly
~add src/extension/src/api/templates to the .gitignore
Possibly will require the following change:
add copying the templates folder to the build script or create a ./build for local development, if it is used by the build pipeline. Or we could just make this copying the manual process.~

**Comment by sibille** [comment]
Agree, local development should be against core dlls built in debug mode, so you can sync templates with the localtemplatesource, that accesses templates folder using a junction pointing directly to the templates folder at the project root. I don't think this requires adding src/extension/src/api/templates to the .gitignore, but just core dlls in debug mode and passing the correct path on sync (we do it this way in WinTS).

**Comment by SahilTara** [comment]
Oh so you mean just changing the path in the build pipeline instead of doing the copying?

Edit: The reason I mentioned the git ignore was due to the redundant templates folder that would result from my solution. If we just change the path in the pipeline for our release this will also work without having to do the git ignore.

**Comment by sibille** [comment]
In WinTS we have a IF debug statement on the code, if your in debug you use the path to the template folder, if you're in release you use the path to the mstx. 
Is there sth like this in React?

**Comment by SahilTara** [comment]
Ah yes, there is! (In node and vscode). Much simpler solution thanks for the input will modify issue to incorporate this. Will need to test it out but I have a hunch on the solution.

**Comment by jsondoo** [comment]
@SahilTara So what would the local development process look like after these changes?

**Comment by SahilTara** [comment]
update templates, hit f5, should see changes in generated code. @jsondoo

**Comment by crutkas** [comment]
why aren't these built off Core during local development?  why are they checked in?

**Comment by SahilTara** [comment]
Not everyone contributing may have/want to use dotnet

**Comment by sibille** [comment]
Is this really an issue? We could do an emulator for the core apis in that case. 
Problems I see with having the dlls on github:
- They can easily get out of sync with whats in the submodule (and it is hard to tell if they are in sync or not)
- Adding the dlls increases a PR with submodule changes a lot, makes it more difficult to review.

**Comment by SahilTara** [comment]
@sibille yeah if you can make an emulator for the core apis that'd be great. In the case where we ./build.
I agree there are issues with keeping them synced though.

Would there be a way to have the pipeline or something autoupdate the dlls everytime we update the submodule?

**Comment by sibille** [comment]
There's always a way, but I don`t think the dll s should be on github ;)
I've opened a separate issue for this (https://github.com/microsoft/WebTemplateStudio/issues/691) If removing them is an really an issue to any collaborator, and we can see what they'd need to be able to collaborate.

**Comment by SahilTara** [comment]
Okay that works, i suppose if anyone doesn't like it we can accommodate them when the time comes. I suppose the reward of removal outweighs the consequences

**Comment by SahilTara** [comment]
Going to close this issue off.
