### ISSUE TITLE
Adding azure resource throws error.  wizard - 0.0.1914003

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WebTemplateStudio#637]
![image](https://user-images.githubusercontent.com/1462282/58527904-74b48100-8189-11e9-9eef-f9a32e5c4ea3.png)

Templates version: 0.0.19140.3
Wizard version: 0.0.1914003

**Comment by jasmingoh** [comment]
Hey @crutkas , do you mind documenting the steps you took that caused the error? Also, it would be awesome if you can try adding resource with a different Azure account. I tried reproducing the error, but it seems like I can't get it (I'm using the same version as the one you mentioned in this issue!).

**Comment by SahilTara** [comment]
@crutkas can you also use the report an issue button to get the stack trace and such.

**Comment by crutkas** [comment]
@sahiltara, i didn't realize that, why isn't the stack trace in the output window?

**Comment by SahilTara** [comment]
My thoughts exactly. Trevor made an issue for this #658

**Comment by streetcoder123** [comment]
@jasmingoh Should we close this issue?
