### ISSUE TITLE
Warning in Browser Console In React List Template

### ISSUE THREAD

**Issue by streetcoder123** [Microsoft/WebTemplateStudio#638]
Steps to reproduce the warning:
- Generate a React application in Web Template Studio
- Do 'yarn install' to install the dependencies and 'yarn start' to run the application
- Go to 'localhost:3000/list' to see the list page and open browser console
- Type something into the form to submit a new list item (you will see the following warning in the console) 

![Capture](https://user-images.githubusercontent.com/35667299/58529805-286d3f00-8191-11e9-8ab6-31716f674fbe.PNG)

**Comment by crutkas** [comment]
Which version of WebTS is this.

**Comment by streetcoder123** [comment]
This shows up when I try to run on local development host. I have not tried it on the version that is up on marketplace yet.
I looked at the code and I think I understand why it is happening there and shall try to fix it tomorrow.

**Comment by crutkas** [comment]
Didn’t you just touch this page’s code base?  https://github.com/microsoft/WebTemplateStudio/pull/629

**Comment by streetcoder123** [comment]
Yes, I did but that issue I think should not be related to this one but I shall verify this for sure.

**Comment by crutkas** [comment]
@njindal239, no matter what, we need some reference to mark code bases against one another. What is your fork currently synced at

**Comment by streetcoder123** [comment]
I am sorry but I do not understand your question. How do I check what my fork is synced at?
UPDATE:
I checked it with the version available on market place:
Template version: 0.0.19140.3
Wizard Version: 0.0.1914003

I was able to replicate the same warning in this version.
