### ISSUE TITLE
code base shouldn't have defaultMessage, instead should have a default resource file

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WebTemplateStudio#657]
src/client/src/components/LeftSidebar/index.tsx 

const messages = defineMessages({
  welcome: {	  welcome: {
    id: "leftSidebar.welcome",	    id: "leftSidebar.newProject",
    defaultMessage: "1. Welcome"	    defaultMessage: "1. New Project"
  },	  },

yet we have en.json which has the same text msg.  This means we have to keep stuff in sync and could have text missing from a resource file.  Resources should default to local, then language then default file.

**Comment by SahilTara** [comment]
en.json is automatically generated from these default messages. We do not have to manually keep things in sync since this automatic after deleting and regenerating the en.json. @crutkas

**Comment by SahilTara** [comment]
Hmm haven't done enough research yet, maybe you have do you know if this is currently supported?  I will continue doing more research on the subject though.

**Comment by SahilTara** [comment]
Hmm, yeah clint doing more research on it I'm pretty sure the en.json is generated from these defaults. I know this is different from the resx approach of C# (It's a flipped approach). I can 100% see where possible concerns could have stemmed from, but in react its flipped where you define the messages in the code and generate the resource file that way (At least for the library we are using). I could be entirely wrong and have missed something but that's what I think.

**Comment by crutkas** [comment]
Hmmm, ok. Still feels like we’ll get into trouble for translation. But on the flip side, it may be easier to do a diff.
