### ISSUE TITLE
Output Channel Logs Need to be more Informative

### ISSUE THREAD

**Issue by trevorNgo** [Microsoft/WebTemplateStudio#658]
![image](https://user-images.githubusercontent.com/23327878/58670548-50c17e80-82f4-11e9-8a45-b93dd0d2bbab.png)

**Comment by trevorNgo** [comment]
I suggest leveraging Telemetry and pulling data from the error parser

**Comment by sibille** [comment]
We've improved logs for sync and generation issues, the shown error is a known issue from Azure Account, where we can't add more info.
