### ISSUE TITLE
Could not run the default CosmosDB SQL queries.

### ISSUE THREAD

**Issue by annielovesjs** [Microsoft/WebTemplateStudio#660]
I get this error when I go on the list page and when I try to submit list items

![cosmosError](https://user-images.githubusercontent.com/31115095/58674222-a8b3b180-8303-11e9-85cc-7fa74fe41379.PNG)

**Comment by SahilTara** [comment]
It says internal server error can you go to the console and show the stack trace or something?

**Comment by SahilTara** [comment]
Oh wait you know what it might be, have you let the env file message pop up yet and clicked yes to .env file auto replacing?

**Comment by SahilTara** [comment]
Cosmos takes approximately 5 mins 45 seconds +- 30s depending on load to deploy, message for env replacement shows up 4 to 10 seconds after.

**Comment by SahilTara** [comment]
Getting these stats from deploying hundreds of cosmos instances while trying to fix bugs and testing out the templates and such.

**Comment by annielovesjs** [comment]
@SahilTara hmm I didn't actually see the env message pop up, I just opened the generated code templates once it was finished deploying cosmosdb (took about 2-3 minutes of loading)

Here are the errors in my terminal when I tried to run it:
![sqlErr](https://user-images.githubusercontent.com/31115095/58719642-105e1100-8385-11e9-89e4-c00729882fef.PNG)

**Comment by annielovesjs** [comment]
@SahilTara I ran it again and saw the env message after waiting a bit longer after it loaded and it seems like it works now. Should we automate the replacement of the display name since it is hard for users to see or know what is causing the error?
![envPic](https://user-images.githubusercontent.com/31115095/58721126-fde5d680-8388-11e9-8e6d-940a11d5afc2.PNG)

**Comment by SahilTara** [comment]
The error is caused because you didnt replace the env file. We do have it automated, check the dev nightly it should say source: web template studio or something of the sort. Also env file is automated as well but we can only automate replacement if they keep the wizard open long enough which is when we do the pop up. The wizard dies after we close it for the most part. Which is why we have close wizard button only pop up once cosmos has deployed and such.

**Comment by SahilTara** [comment]
I would say that having a better error message would be useful though maybe doing a check to see if the env file is default or not?

**Comment by annielovesjs** [comment]
I see... In that case, maybe we could  also disable the close wizard button until the popup receives a response from the user

**Comment by SahilTara** [comment]
Yeah that could work, or just don't show the close button until the user has picked an option. I think it shows the close wizard button when the pop up is about to show/has shown currently.

**Comment by SahilTara** [comment]
@annielovesjs
https://github.com/microsoft/WebTemplateStudio/blob/f5cf75d037c12c910719196da01e0f5ef811435c/src/extension/src/generationExperience.ts#L144-L159

Perhaps using an await here might help you? Instead of using a .then(). Not sure but that's my hunch.
