### ISSUE TITLE
Remove 'back' button on first step of wizard

### ISSUE THREAD

**Issue by jsondoo** [Microsoft/WebTemplateStudio#664]
@jasmingoh @xtinah-w performed a lot of user research this week, and one major complaint was the 'Back' button on the first step of the wizard (it should either be disabled or removed because it looks clickable currently)

**Comment by SahilTara** [comment]
Do you have any ideas on how to keep the look and feel native + making the button look more disabled than it is currently?


![image](https://user-images.githubusercontent.com/32103099/58736769-04963d00-83cd-11e9-9746-664736eca4c2.png)
vs
![image](https://user-images.githubusercontent.com/32103099/58736778-0fe96880-83cd-11e9-98f6-958390469a9f.png)

Also, if we remove the back button will it hurt UI consistency or is the trade off okay?

**Comment by AdrianoCahete** [comment]
I'm not a contributor neither a MS employee, but I'll give my 2 cents:

> Do you have any ideas on how to keep the look and feel native + making the button look more disabled than it is currently?
The buttons actually has a pointer cursor even with the disable state. Remove it and leave just for the active buttons.

> if we remove the back button will it hurt UI consistency or is the trade off okay?

As a UX person, I see a "disabled" button like a button that can work in a page if a "certain criteria is met". In other words, the "Back" button just needs to be shown if something change and it needs to be available.

This definition will throw a few questions that will help you to answer this question:
- It's the first page. You need to have a back button enabled in the first page?
- If the "Back" button can be enabled in some case(s), this button will send user back to any page/step, in this page?

I don't mind to break the consistency if it's will help the user.

**Comment by crutkas** [comment]
@AdrianoCahete great feedback

I'd also like to comment and reiterate, this is a community lead project.  While we have MSFT employees working on it, we welcome feedback, issues and contributions.  Feedback is just as valuable as PR's.  So let me just say, thank you

**Comment by jsondoo** [comment]
Closing, resolved by #820
