### ISSUE TITLE
Angular navigation not using routerLink

### ISSUE THREAD

**Issue by xWiiLLz** [Microsoft/WebTemplateStudio#665]
https://github.com/microsoft/WebTemplateStudio/blob/f5cf75d037c12c910719196da01e0f5ef811435c/templates/Web/_composition/AngularJS/Page.Angular.AddNavItem/src/app/components/NavBar/navbar.component_postaction.html#L5

The navigation links are not using routerLink, which makes them reload the entire page rather than leveraging angular's router.

Should be changed to `routerLink="wts.ItemName"`.

**Comment by SahilTara** [comment]
Seems like we did the same thing in angular as we did in react! Good call out! Thankfully we didn't make the same mistake in Vue.
