### ISSUE TITLE
Angular naming conventions should be respected

### ISSUE THREAD

**Issue by xWiiLLz** [Microsoft/WebTemplateStudio#668]
I guess this issue requires a lot of minor changes, but it is very important since the goal of WebTS is to generate code that follows _best patterns and practices_. Since the goal here is to support Angular, the scaffolded code should follow [Angular's Style Guide](https://angular.io/guide/styleguide). Following is a non-exhaustive list of changes to be made in the current code:

- [x] Output() properties should not be suffixed with `EventEmitter`, nor should they be prefixed with `on`. [Reference](https://angular.io/guide/styleguide#avoid-aliasing-inputs-and-outputs)
- [x] Folders & filenames should all be [kebab-case only](https://angular.io/guide/styleguide#symbols-and-file-names).
- [ ] Router modules should be separated from their modules, and the main routing-module should reflect all that's possible within the app. Currently, when looking up the AppModule's routing, it's impossible to know that there are other routes in the app. (_Modules should also be lazy-loaded, since it isn't much work added and shows best practices in terms of bundling size_)
- [x] Properties should not be prefixed with underscores `_`. 
i.e. **ListFormComponent** has `_textField`, which is even more odd since it's actually public by default
- [x] Useless getters/setters should be avoided (_ListFormComponent_)
- [x] Assets should always be included from the `assets/` folder (svg images as well)

If any other Angular Developers would like to hop in and fill in other critical styling issues, we could address all of the related issues in this thread.

One **critical point** is that, in its current state, the generated code **does not even pass** its own generated linting file. I think this should be addressed quickly, as it does not give out a good first glance about the quality of what's being generated.

**Comment by manekinekko** [comment]
Hi, here are few quick notes (from interal discussion with @Tanya0609 ):
- [ ] the content of the src/constants.ts should be moves to the environment files under src/environments
- [ ] the files under src/app/images should be moves to the assets folder src/assets and use the MatIconModule to register and use the SVG assets (see https://material.angular.io/components/icon/api)
- [ ] you may wanna move the WarningComponent under src/app/shared/warning/ (to be created)
- [ ] I'd rename src/app/components to src/app/app-shell
- [ ] all folders and symbol names should be in lower kebab case, eg, Master_Details.module.ts --> master-details.moduke.ts
- [ ] I'd probably move the interface definitions from the components to their related services, eg, IGridTextItem in src/app/components/Grid/GridBox/grid-box.component.ts should be moved to src/app/components/Grid/grid.service.ts
- [ ] make sure you run the ng lint command to fix  all formatting issues (if any). You may wanna make also sure the app is building in prod mode.
- [ ] We released Angular version 8 yesterday, you may wanna give it a shot 😉
- [ ] I was also wondering if you are planning to add some tests (if that is relevant)?

Let me know if you need anything else.

**Comment by Tanya0609** [comment]
We will collect those feedback under issue #681

**Comment by Tanya0609** [comment]
"Router modules should be separated from their modules, and the main routing-module should reflect all that's possible within the app. Currently, when looking up the AppModule's routing, it's impossible to know that there are other routes in the app. (Modules should also be lazy-loaded, since it isn't much work added and shows best practices in terms of bundling size)"

Had discussion with @xWiiLLz: Since our current generated code doesn't have a separate Module's routing file for each file and some of the components aren't properly generated (missing few files). Thus, we will address this suggestion along with file structure together.

I will put this under a different GitHub Issue #681.
