### ISSUE TITLE
Pages are draggable way beyond where they should be

### ISSUE THREAD

**Issue by SahilTara** [Microsoft/WebTemplateStudio#671]
Hey, right now we have a sortable list component which allows us to reorder our items via dragging. But there are a lot of visual bugs possible with this. Such as picking it up and dragging it across the screen if translated via the x axis, and if translated via the y axis something like this:
![notfixed](https://user-images.githubusercontent.com/32103099/58757255-2d0a5e00-84d7-11e9-8f87-8018a87eb130.gif)

This should be a simple fix within the client side. Probably has to do with the sortable selection list component. If you need help with this please discuss in this issue. I will be more than willing to help.

**Comment by Hardik500** [comment]
I would like to work on this issue any idea on how can I get started?

**Comment by SahilTara** [comment]
We use [react-sortable-hoc](https://github.com/clauderic/react-sortable-hoc) to do our sortable lists. You might want to look at lock axis to at least bound to the y axis. Figuring out the proper way to constrain the pages is a bit harder. You can do something quick with lockOffset possibly but is that the best way? Should explore and see what you can come up with. This change probably needs to happen in the [Sortable Selection List](https://github.com/microsoft/WebTemplateStudio/blob/dev/src/client/src/components/SortableSelectionList/index.tsx) component. The attributes listed in the docs get applied to the Sortable Summary inside!  @Hardik500

**Comment by Hardik500** [comment]
So basically we want to lock it so that it doesn't go off bounds to its container.
@SahilTara

**Comment by Hardik500** [comment]
I have tried several ways but I can't seem to find a certain fix to your issue. Maybe I will try it later on when I will get a grasp on react.

**Comment by sibille** [comment]
We should review the whole drag + drop logic, the dragged item is not shown in the right pane while dragging + text gets selected when mouse moves over other items.

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.0.19329.1
Wizard version: 0.0.1932901
