### ISSUE TITLE
When sync templates finish, should have a feedback

### ISSUE THREAD

**Issue by Tanya0609** [Microsoft/WebTemplateStudio#685]
At the moment if someone launches the extension, when launching finishes and user starts select frameworks, the frameworks won't show up because the sync hasn't finished.

**Comment by SahilTara** [comment]
Yeah for some reason sync has broken down, it used to have complete feedback and wouldn't let you pass unless you even reach the wizard without sync. I noticed it on something nipun sent me once. Really strange its even letting people into the wizard.

**Comment by SahilTara** [comment]
It used to say something like "Failed to sync" or something

**Comment by sibille** [comment]
Is this happening on the local development environment or the published vsix?

**Comment by Tanya0609** [comment]
It was on local development environment

**Comment by Tanya0609** [comment]
This issue should be resolved by calling corets cli and I could no longer produce this bug any more, thus close this issue
