### ISSUE TITLE
Uppercase in project name creates problem

### ISSUE THREAD

**Issue by neminovno** [Microsoft/WebTemplateStudio#689]
Having `"name": "MyProject"` in _package.json_ creates following problem:

> String does not match the pattern of "^(?:@[a-z0-9-~][a-z0-9-._~]*/)?[a-z0-9-~][a-z0-9-._~]*$".

**Comment by jasmingoh** [comment]
Thanks for reporting @neminovno 

Just to add more context, here are the steps to reproduce:
1. In the Welcome page of the extension, put "MyProject" as the Project Name.
2. Step through all other steps
3. Open the generated project, and go to package.json.
![image](https://user-images.githubusercontent.com/20333350/59053662-c7a3cd80-8846-11e9-8a6c-3af4fe946b3e.png)

**Comment by SahilTara** [comment]
Hmm perhaps when we get the kebab case going for angular we can utilize the solution to fix this as well

**Comment by Tanya0609** [comment]
what type of frameworks did you use when using this name?

**Comment by SahilTara** [comment]
Like allowing this type of name to be entered/casing?

**Comment by SahilTara** [comment]
Or are you asking the poster?

**Comment by neminovno** [comment]
> 
> 
> what type of frameworks did you use when using this name?

@Tanya0609 In available one - React.

**Comment by sibille** [comment]
we can use a dotnet template engine transform to transform the project name to lowercase like for example angular cli does.

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.0.19339.1
Wizard version: 0.0.1933901
