### ISSUE TITLE
Implement 'Add authentication' as option that generates frontend and backend authentication related code

### ISSUE THREAD

**Issue by neminovno** [Microsoft/WebTemplateStudio#697]
Provide new option:

- [ ] Add authentication

and if user clicks/selects it, that should generate frontend and backend authentication related code. For example:

- during project creation, if available, user can select authentication type
- in React `Login` component should be available, maybe `PrivateRoute`s in `App` for Pages selected to be private?...
- in Express authenticating requests is implemented in server code depending on user choosen authentication type

**Comment by xtinah-w** [comment]
This feature is contained/similar to #608

**Comment by neminovno** [comment]
Yes it is, sorry I missed it. In mine case it is React option, in #608 it is Angular, but the point of the issue is the same.

**Comment by xtinah-w** [comment]
@neminovno No worries, we were cleaning up the issues and going through ones that we wanted to tackle :)

**Comment by neminovno** [comment]
@xtinah-w Great, I am glad this is one to tackle :)

**Comment by sibille** [comment]
Closing in favor of  #608.
