### ISSUE TITLE
Vue URL not consistent with React and Angular

### ISSUE THREAD

**Issue by Tanya0609** [Microsoft/WebTemplateStudio#699]
Issue: when start the url, it has addtional # in the url. And npm start did not open the project automaticly in my default browser (chrome)

How to reproduce:
1. generate a project with Vue and blank page selected
2. start the project

Vue Url: 
![vue-url](https://user-images.githubusercontent.com/12874317/59138490-47fb2900-8942-11e9-8b1a-4a9c0f847a5c.PNG)

React Url & Angular Url: 
![react-url](https://user-images.githubusercontent.com/12874317/59138531-809b0280-8942-11e9-832f-c72cab91c326.PNG)

**Comment by SahilTara** [comment]
Think you can add --open to the start-client script for vue.

**Comment by SahilTara** [comment]
Also to get rid of the hash you have to switch routing modes. Its not a huge deal to me personally but I totally understand the need for consistency heres the link to a guide from the [official docs](https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations). It makes the urls look a lot nicer though!!
