### ISSUE TITLE
Flask icon is very difficult to see

### ISSUE THREAD

**Issue by SahilTara** [Microsoft/WebTemplateStudio#733]
In dark mode the current flask icon is very difficult to see.

![image](https://user-images.githubusercontent.com/32103099/59476613-98312a00-8e1f-11e9-9ede-9c8d71055cdb.png)

One possible fix is having a light variant of the icon, and swapping to it when the theme is dark enough.

**Comment by jsondoo** [comment]
Actually our designer @xtinah-w just made a Flask logo svg with a white background, I will update it soon
