### ISSUE TITLE
Abstract 'Concurrently' Dependency to FullStack Application template

### ISSUE THREAD

**Issue by streetcoder123** [Microsoft/WebTemplateStudio#735]
'Concurrently' Dependency in the dev Depedendencies of back-end frameworks should be abstracted to the Full Stack Application template file
The reason is we need this dev dependency only if we are using Full Stack Application. It is not required for independent front-end and back-end applications.

**Comment by njindal239** [comment]
'Concurrently' Dependency in the dev Depedendencies of front-end frameworks should be abstracted to the Full Stack Application template file
The reason is we need this dev dependency only if we are using Full Stack Application. It is not required for independent front-end and back-end applications.
