### ISSUE TITLE
Wizard does not start again until you re-open vscode

### ISSUE THREAD

**Issue by streetcoder123** [Microsoft/WebTemplateStudio#756]
After one project is generated, if we try to generate another project, the wizard does not start up. It works if we close the extension and launch it again.

**Comment by SahilTara** [comment]
What do you mean when you say "If we try to generate another project"? Can you list the full set of steps? Are you trying to make it so that right when you do "Ctrl shift p" It launches another instance of the wizard? Just curious

**Comment by streetcoder123** [comment]
@SahilTara So, following are the steps:
- Run the extension using F5
- Launch the wizard using Ctrl+Shift+P
- Close the wizard (not the vscode window)
- Launch the wizard again using Ctrl+Shift+P (It does not launch at this time)

This was the issue that happened sometime while refactoring extension logic into CoreTemplateStudio.ts.
I was fixed in this PR: https://github.com/microsoft/WebTemplateStudio/pull/757
