### ISSUE TITLE
Customize project type and frameworks

### ISSUE THREAD

**Issue by saggir** [Microsoft/WebTemplateStudio#778]
Hi,
How can I customize the extention to support other project types and framewroks?

We have internal specific project types that we want to support and generate configurable projects.

Thanks,
Saggi

**Comment by jsondoo** [comment]
Hey @saggir,

What do you mean by customize the extension? If you want to try other frameworks, we have additional frameworks in preview mode (Flask and Vue), which you can turn on in your settings in vscode.

**Comment by jcoc611-microsoft** [comment]
In general, the data about the templates is in the `/templates` [directory](https://github.com/microsoft/WebTemplateStudio/tree/dev/templates). The metadata of each project type and framework is in the `/templates/_catalog` [directory](https://github.com/microsoft/WebTemplateStudio/tree/dev/templates/_catalog), and the actual template files are in `/templates/Web` [directory](https://github.com/microsoft/WebTemplateStudio/tree/dev/templates/Web). The docs on the templating system is on the sister project Windows Template Studio, you can read those docs [here](https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/templates.md).

**Comment by sibille** [comment]
Configuration of custom template sources is not supported yet, sorry. You can fork the project and adapt the templates as Juan described as a workaround.
