### ISSUE TITLE
Checkmark for azure services forms are yellow

### ISSUE THREAD

**Issue by jsondoo** [Microsoft/WebTemplateStudio#823]
![image](https://user-images.githubusercontent.com/21695878/60634936-ad1d2f80-9dc5-11e9-860d-7ba2010ccd45.png)

Checkmark for both Azure Functions and Azure Cosmos DB forms are yellow (it should be green). It seems like VS Code theme variables were updated.

**Comment by streetcoder123** [comment]
@jsondoo Where do you see this change? I am not able to reproduce this on dev branch.

**Comment by jsondoo** [comment]
![image](https://user-images.githubusercontent.com/21695878/60680145-12f9cd80-9e3f-11e9-9108-9ebcdddc86f7.png)

I think with the new vscode release on 1.36 
My tslint underline changed from green to yellow too
