### ISSUE TITLE
Issues with accessibility in Lightmode for Dependency Checker

### ISSUE THREAD

**Issue by SahilTara** [Microsoft/WebTemplateStudio#838]
![image](https://user-images.githubusercontent.com/32103099/60753294-0f308d00-9f9e-11e9-8b85-4b00406683c6.png)

Yellow on white is not greatly readable. 

Credits to @ngkelly3 for pointing out this issue.

I think a good practice from now on is to test all designs in light, dark, and high contrast modes. Maybe even play around with it a bit in other themes. But it should be good for light dark and high contrast modes at all times.

@jsondoo @xtinah-w  Thoughts?

**Comment by ngkelly3** [comment]
This as well: 
![image](https://user-images.githubusercontent.com/16379350/60753412-b0abe480-9f86-11e9-9468-93a189110df1.png)

VSCode recommends that extensions should support light, dark and high contrast at the very least. Toggling the VSCode developer tools will give you access to the inspector, which will provide the various CSS variables and their colour codes that VSCode uses for colour theming. In general, as long as you use a variable that has a colour that works in one theme, it will translate across other themes.

**Comment by jsondoo** [comment]
> VSCode recommends that extensions should support light, dark and high contrast at the very least. Toggling the VSCode developer tools will give you access to the inspector, which will provide the various CSS variables and their colour codes that VSCode uses for colour theming. In general, as long as you use a variable that has a colour that works in one theme, it will translate across other themes.

I never knew about vscode developer tool until now so this should be helpful. We will be more careful designing for and supporting at least light, dark and high contrast from now on (we did consider themes for stuff like Flask logo but definitely overlooked it for other things). I agree that right now it's not very readable on light theme, thanks for pointing this out.
