### ISSUE TITLE
Some Azure function location in the drop down menu does not work

### ISSUE THREAD

**Issue by jasmingoh** [Microsoft/WebTemplateStudio#847]
As mentioned by @SahilTara in this https://github.com/microsoft/WebTemplateStudio/pull/824#issuecomment-508840498, there is a bug in Azure SDK.

It seems like Azure Functions are only supported in regions where there is pricing information from this website: https://azure.microsoft.com/en-us/pricing/details/functions/

**Comment by streetcoder123** [comment]
@jasmingoh Is this still an isssue?

**Comment by jasmingoh** [comment]
Yes, this is still an issue

**Comment by sibille** [comment]
Closing this as we don't generate Azure functions anymore.
