### ISSUE TITLE
Create New Project default output path bug

### ISSUE THREAD

**Issue by jasmingoh** [Microsoft/WebTemplateStudio#872]
Please refer here: https://github.com/microsoft/WebTemplateStudio/pull/861#issuecomment-510138295

Create New Project logics need to take default output path into consideration, and the error box under output path should not be showing by default

![image](https://user-images.githubusercontent.com/20333350/61000421-37a7e680-a312-11e9-9dd2-f85f97169e10.png)

**Comment by xtinah-w** [comment]
Also need to disable input completely and remove user's ability to type their own "Save To" destination

**Comment by SahilTara** [comment]
Think this issue can be closed now

**Comment by jsondoo** [comment]
Closing this - fixed with #893 

> Also need to disable input completely and remove user's ability to type their own "Save To" destination

Fixed with #928
