### ISSUE TITLE
Would you take a pull-request that adds WebAssembly templates?

### ISSUE THREAD

**Issue by ghuntley** [Microsoft/WebTemplateStudio#879]
Howdy folks, 👋 

I'm wondering if you would take a pull-request that adds a template option that provisions a webassembly application, configured with sensible defaults, that is integrated with azure? 

ie. file -> new -> https://calculator.platform.uno (see also https://visualstudiomagazine.com/articles/2019/06/27/uno-calculator.aspx)

**Comment by Tanya0609** [comment]
Hi @ghuntley, thank you for proposing the idea. Just wondering, what are the user group of WebAssembly? Is this a language commonly been used to prototype/build a web project? Will someone be able to help to maintain it in a long run?

Our target users are web application programming learners, intermediate level developers.
