### ISSUE TITLE
Disable the "-" button when you can't use it on pages

### ISSUE THREAD

**Issue by xtinah-w** [Microsoft/WebTemplateStudio#892]
When users can't remove a page, we should hide the - button and show it when it applies again.

**Comment by SahilTara** [comment]
Can we figure out a way to do this without making it look odd (since when @njindal239 was adding the + button only it looked very strange)? Why not just change the opacity of the button/make increasingly greyed out?

**Comment by streetcoder123** [comment]
Yeah, we are thinking of changing the style on that one so that it appears as not clickable, probably as you said more greyed out.

**Comment by xtinah-w** [comment]
@SahilTara Thanks for the suggestion, we are planning to disable it! Hide was a bad word to describe it!
