### ISSUE TITLE
"Working" looks like it's an active button when it's generating the project 

### ISSUE THREAD

**Issue by xtinah-w** [Microsoft/WebTemplateStudio#897]
Need to come up with a new design to respect the blue colour attribute throughout the system
![workingScreenshot](https://user-images.githubusercontent.com/24245311/61093656-6ac8a380-a400-11e9-8b4e-97770203014d.PNG)

**Comment by SahilTara** [comment]
Maybe use the black button here + disable?

**Comment by xtinah-w** [comment]
Thanks for the suggestion, Sahil! I'll look into this and propose it to @jsondoo as an option.

**Comment by SahilTara** [comment]
Think this is closed as of #946
