### ISSUE TITLE
Change "Save to" field on home to "Browse" button

### ISSUE THREAD

**Issue by xtinah-w** [Microsoft/WebTemplateStudio#898]
Currently, most users are clicking on the Folder icon to add their "Save To" destination. Bugs have been submitted continuously where users are inputting random output paths and breaking the system.

We will be changing this to a button that opens a window where users will select where they want to save their project.

**Comment by jsondoo** [comment]
@xtinah-w could you post the design here once it's ready? thanks :)

**Comment by xtinah-w** [comment]
@jsondoo can you let me know if you're happy with this design? Any other changes, lmk.

![Output Destination - Step 1](https://user-images.githubusercontent.com/24245311/61238608-db6a0b80-a6f1-11e9-98d1-9520f15552c2.png)
![Output Destination - Step 2](https://user-images.githubusercontent.com/24245311/61238609-db6a0b80-a6f1-11e9-9ce9-9518abcefd50.png)

**Comment by xtinah-w** [comment]
Should we have the browse button on the left or right?
![browse-button-left](https://user-images.githubusercontent.com/24245311/61335767-8a3a4480-a7e3-11e9-9a3d-8bb1bbd796c4.png)
![browse-button-right](https://user-images.githubusercontent.com/24245311/61335768-8a3a4480-a7e3-11e9-862a-968cf876fb53.png)

**Comment by jsondoo** [comment]
this design is outdated, we kinda redid the design as we went today
