### ISSUE TITLE
Make the wizard responsive at 400px min-width

### ISSUE THREAD

**Issue by xtinah-w** [Microsoft/WebTemplateStudio#900]
Hide the right bar (until summary page) when wizard reaches smallest window size and ensure everything is resizing properly in case someone has a lower screen DPI or using split editor mode.

**Comment by Tanya0609** [comment]
@xtinah-w  @annielovesjs will this issue be fixed by this PR? #954

**Comment by annielovesjs** [comment]
@Tanya0609 Yup! This issue is now resolved
