### ISSUE TITLE
Users should receive a warning before they sign out of Azure

### ISSUE THREAD

**Issue by xtinah-w** [Microsoft/WebTemplateStudio#901]
There is currently no user feedback if a user accidentally clicks sign out in the Azure page.

**Comment by SahilTara** [comment]
Hmm, yeah if there's items in the cart related to azure it should warn 100%. if not should it or should it not?

**Comment by xtinah-w** [comment]
It should warn 100% of the time because currently the "Log Out" isn't part of a 2-part click process which is typically how most systems prevent accidental log outs (finding the menu and navigating to log out). It's just displayed as a blue link button and it takes time investment from the user's side to actually try and sign in.

As a result, a 2-click log out process should be more standard and this would be the simplest way to address the issue. If they have accidentally signed out, it would take at least 3 additional clicks to sign back in, including taking the user out of the wizard itself which is annoying.
