### ISSUE TITLE
Add a Quick Start Feature to the Wizard

### ISSUE THREAD

**Issue by streetcoder123** [Microsoft/WebTemplateStudio#925]
There should be a quick start button in the welcome page of the wizard. Clicking on that button will directly take the user to the summary page with default configurations (ReactJS Frontend, NodeJS Backend and a blank page selected). 

This would accelerate the user to create the project without having to go through all the steps of the wizard. The user would still be able to go back to any page after going to summary page (through quickstart) for making any modifications to default selections.

**Comment by streetcoder123** [comment]
@xtinah-w Can you upload the updated design for quickStart?

**Comment by xtinah-w** [comment]
![quickStart](https://user-images.githubusercontent.com/24245311/61410255-d72c2280-a898-11e9-98a1-b6128aa80f38.png)
