### ISSUE TITLE
Inconsistent right side bar

### ISSUE THREAD

**Issue by annielovesjs** [Microsoft/WebTemplateStudio#937]
- right side bar is bigger on the azure page due to the added scroll bar

**Comment by Tanya0609** [comment]
@annielovesjs Is this issue should be fixed by Pitor and your PR? 
https://github.com/microsoft/WebTemplateStudio/pull/954

**Comment by sibille** [comment]
Verified in nightly version:
Templates version: 0.3.21127.1
Wizard version: 0.3.2112701
