### ISSUE TITLE
SVG's overwrite each other's CSS classes

### ISSUE THREAD

**Issue by jsondoo** [Microsoft/WebTemplateStudio#967]
Having multiple svg's in one view overwrrite each other's CSS classes resulting in weird colors because all svg's use the same classnames 

(e.g. adding azure functions overwrites the planet color's `.cls-2`)
![image](https://user-images.githubusercontent.com/21695878/62090108-85808200-b220-11e9-8755-cd7e7289f6b5.png)

(e.g. azure services page which has a lot of svgs)
![image](https://user-images.githubusercontent.com/21695878/62090174-be205b80-b220-11e9-8a9e-2e453bd12c84.png)

**Comment by SahilTara** [comment]
@jsondoo I have a fix for this, gonna wait for the role pr to go in first.

**Comment by SahilTara** [comment]
So there's two ways to fix this 
1) make all class names unique in svgs
2) Set all svgs as src inside of img instead.

Which do you prefer?

**Comment by jsondoo** [comment]
@SahilTara I think the second solution is better or easier for you to implement. Thanks :)

**Comment by SahilTara** [comment]
@jsondoo I made a script to automate first option just in case you asked haha

**Comment by jsondoo** [comment]
@SahilTara ohh nice, if the script is ready then just go with the first

our original plan was to update all the svg's classnames anyways

**Comment by SahilTara** [comment]
Yeah, need to wait for #969 to get merged first!
