### ISSUE TITLE
Quick Start Enhancement

### ISSUE THREAD

**Issue by streetcoder123** [Microsoft/WebTemplateStudio#972]
Quick Start should be enhanced such that:
- It is more obvious that it is optional to take the quick start route.
- Add new information to summary page if user arrives there through quick start.

**Comment by xtinah-w** [comment]
![quickStart-v3](https://user-images.githubusercontent.com/24245311/62169262-9e4e6d80-b2dc-11e9-8e3d-3e8e05da7c3b.png)
![quickStart-end](https://user-images.githubusercontent.com/24245311/62169265-a1e1f480-b2dc-11e9-8b39-3b97c1919724.png)


Quick Start copy has changed + Quick Start summary message will change if users have activated it
