### ISSUE TITLE
Feedback on Generated VueJS Code

### ISSUE THREAD

**Issue by ali-kha** [Microsoft/WebTemplateStudio#978]
Summary of issues and suggestions from vue experts
- Use Vue short hands 
  - ie. `v-bind:foo` should be `:foo`
- Use @ for paths instead of relative ones
- Don't use bootstrap! 
- Use `foo()` instead of `foo: function()` for component fields
- Use object syntax for competent props
- Improve names of reusable components
  - ie. `WarningMessage` should be `BaseWarningMessage` 
- On the Vue styling guide, make sure to follow recommended styling as well, not just the essential

**Comment by SahilTara** [comment]
Is removing bootstrap a good idea? Mainly because its used in our other 2 front end frameworks. Just wondering.

**Comment by streetcoder123** [comment]
@SahilTara We thought about this as well. I think we shall be settling on using `bootstrap-vue` to be consistent with other frameworks and have something explicit for vue as well.
