### ISSUE TITLE
Move "Create New" subscription into the dropdown selection menu

### ISSUE THREAD

**Issue by xtinah-w** [Microsoft/WebTemplateStudio#996]
If a new user has no subscriptions, they should be able to see "Create New" as the call to action when they click on the dropdown menu.
![createNewDropdown-azureForms](https://user-images.githubusercontent.com/24245311/62324022-73d7ee00-b45d-11e9-8f0e-3cee8562b09e.png)

Also, another UX problem is that once a user successfully creates a subscription or resource group outside of the wizard at the same time, they have to manually refresh it themselves. Need to figure out a way for the user to be able to populate this once they return from the browser.

**Comment by prupipho** [comment]
True that when adding a new subscription it doesn´t appear automatically. As a quick test I did logged out and logged back in to see the new subscription appearing on the list. Maybe new issue for this one @sibille ?

This has changed already. Not in the dropdown but always visible as a link:
![image](https://user-images.githubusercontent.com/1333036/96700229-822a6680-138f-11eb-90a1-cc90bb942e24.png)
![image](https://user-images.githubusercontent.com/1333036/96700252-88b8de00-138f-11eb-99eb-98698675ed0c.png)

**Comment by sibille** [comment]
@prupipho I Agree, this should have a refresh button next to the subscription list, similar to the one for the ressource group.
![image](https://user-images.githubusercontent.com/24698018/96703631-61fca680-1393-11eb-8d0b-ea4e9e7a4334.png)
I'll create a separate issue for this.
